export const projectsData = [
 {
    id: 1,
    slug: "jaipur-clubhouse",
    title: "jaipur clubhouse",
    category: "club house",
    image: "/jaipur clubhouse/cover image.webp",
    heroImg: "/jaipur clubhouse/12.webp",
    mainImg: "/jaipur clubhouse/13.webp",
    gridImages: [
      { id: 2, title: "Tech Hub", category: "Interior", image: "/jaipur clubhouse/1.webp" },
      { id: 3, title: "Main Lobby", category: "Design", image: "/jaipur clubhouse/2.webp" },
      { id: 4, title: "Zen Garden", category: "Landscape", image: "/jaipur clubhouse/3.webp" },
      { id: 5, title: "Executive Suite", category: "Interior", image: "/jaipur clubhouse/4.webp" },
      { id: 6, title: "Conference Room", category: "Design", image: "/jaipur clubhouse/5.webp" },
      { id: 7, title: "Staff Lounge", category: "Interior", image: "/jaipur clubhouse/6.webp" },
      { id: 8, title: "Modern Facade", category: "Architecture", image: "/jaipur clubhouse/7.webp" },
      { id: 9, title: "Waiting Area", category: "Design", image: "/jaipur clubhouse/8.webp" },
      { id: 10, title: "Workstation", category: "Interior", image: "/jaipur clubhouse/9.webp" },
      { id: 11, title: "Cafeteria", category: "Design", image: "/jaipur clubhouse/10.webp" },
      { id: 12, title: "Outdoor Seating", category: "Landscape", image: "/jaipur clubhouse/11.webp" },
      { id: 14, title: "Corridor View", category: "Design", image: "/jaipur clubhouse/12.webp" },
      { id: 15, title: "Breakout Zone", category: "Interior", image: "/jaipur clubhouse/13.webp" },
      { id: 17, title: "Garden View", category: "Landscape", image: "/jaipur clubhouse/14.webp" },
      { id: 18, title: "Waiting Area", category: "Design", image: "/jaipur clubhouse/8.webp" },
    ],
    testimonial: {
      userImg: "/jaipur clubhouse/cover image.webp"
    }
  },
  {
    id: 2,
    slug: "kenya-residence",
    title: "kenya residence",
    category: "residence",
    image: "/ProImgs/Proj/kenya-card_result.webp",
    heroImg: "/ProImgs/kenya/kenya-hero_result.webp",
    mainImg: "/ProImgs/kenya/kenya1_result.webp",
    description: "Horizon Office is a futuristic workspace designed for high-performance teams. The interior promotes collaboration with open layouts and modular furniture. We integrated smart lighting systems that adjust based on natural light levels, significantly reducing energy consumption while maintaining a vibrant work environment.",
    stats: [
      { label: "status:", value: "under construction" },
      { label: "year:", value: "2027" },
      { label: "type:", value: "residence" },
      { label: "size:", value: "35,000 sq.ft." },
    ],
    gridImages: [
      // { id: 1, title: "Main Entrance", category: "Exterior", image: "/ProImgs/kenya/kenya1_result.webp" },
      { id: 2, title: "Tech Hub", category: "Interior", image: "/ProImgs/kenya/kenya2_result.webp" },
      { id: 3, title: "Main Lobby", category: "Design", image: "/ProImgs/kenya/kenya3_result.webp" },
      { id: 4, title: "Zen Garden", category: "Landscape", image: "/ProImgs/kenya/kenya4_result.webp" },
      { id: 5, title: "Executive Suite", category: "Interior", image: "/ProImgs/kenya/kenya5_result.webp" },
      { id: 6, title: "Conference Room", category: "Design", image: "/ProImgs/kenya/kenya6_result.webp" },
      { id: 7, title: "Staff Lounge", category: "Interior", image: "/ProImgs/kenya/kenya7_result.webp" },
      { id: 8, title: "Modern Facade", category: "Architecture", image: "/ProImgs/kenya/kenya8_result.webp" },
      { id: 9, title: "Waiting Area", category: "Design", image: "/ProImgs/kenya/kenya9_result.webp" },
      { id: 10, title: "Workstation", category: "Interior", image: "/ProImgs/kenya/kenya10_result.webp" },
      { id: 11, title: "Cafeteria", category: "Design", image: "/ProImgs/kenya/kenya11_result.webp" },
      { id: 12, title: "Outdoor Seating", category: "Landscape", image: "/ProImgs/kenya/kenya12_result.webp" },
      // { id: 13, title: "Boardroom", category: "Interior", image: "/ProImgs/kenya/kenya13_result.webp" },
      { id: 14, title: "Corridor View", category: "Design", image: "/ProImgs/kenya/kenya14_result.webp" },
      { id: 15, title: "Breakout Zone", category: "Interior", image: "/ProImgs/kenya/kenya15_result.webp" },
      { id: 16, title: "Lighting Concept", category: "Design", image: "/ProImgs/kenya/kenya16_result.webp" },
      { id: 17, title: "Garden View", category: "Landscape", image: "/ProImgs/kenya/kenya17_result.webp" },
      { id: 18, title: "Aerial Perspective", category: "Architecture", image: "/ProImgs/kenya/kenya18_result.webp" },
      { id: 19, title: "Final Look", category: "Interior", image: "/ProImgs/kenya/kenya19_result.webp" },
    ],
    testimonial: {
      text: "Our office is now a place where people actually want to come and work. It has boosted our productivity and brand image.",
      name: "ramesh kumar",
      location: "delhi",
      userImg: "/Testimonials/user2.jpg"
    }
  },

  {
    id: 3,
    slug: "dubai-residence",
    title: "dubai residence",
    category: "residence",
    image: "/ProImgs/Proj/dubai-card_result.webp",
    heroImg: "/ProImgs/dubai/dubai-hero.webp",
    mainImg: "/ProImgs/dubai/dubai2.webp",
    description: "Horizon Office is a futuristic workspace designed for high-performance teams. The interior promotes collaboration with open layouts and modular furniture. We integrated smart lighting systems that adjust based on natural light levels, significantly reducing energy consumption while maintaining a vibrant work environment.",
    stats: [
      { label: "status:", value: "under construction" },
      { label: "year:", value: "2027" },
      { label: "type:", value: "residence" },
      { label: "size:", value: "35,000 sq.ft." },
    ],
    gridImages: [
      { id: 1, title: "Entrance View", category: "Interior", image: "/ProImgs/dubai/dubai1.webp" },
      // { id: 2, title: "Main Lobby", category: "Design", image: "/ProImgs/dubai/dubai2.webp" },
      { id: 3, title: "Zen Garden", category: "Landscape", image: "/ProImgs/dubai/dubai3.webp" },
      { id: 4, title: "Living Space", category: "Interior", image: "/ProImgs/dubai/dubai4.webp" },
      { id: 5, title: "Modern Kitchen", category: "Design", image: "/ProImgs/dubai/dubai5.webp" },
      { id: 6, title: "Master Bedroom", category: "Interior", image: "/ProImgs/dubai/dubai6.webp" },
      { id: 7, title: "Balcony View", category: "Exterior", image: "/ProImgs/dubai/dubai7.webp" },
      { id: 8, title: "Guest Suite", category: "Interior", image: "/ProImgs/dubai/dubai8.webp" },
      { id: 9, title: "Private Lounge", category: "Design", image: "/ProImgs/dubai/dubai9.webp" },
      { id: 10, title: "Dining Area", category: "Interior", image: "/ProImgs/dubai/dubai10.webp" },
      { id: 11, title: "Facade Detail", category: "Architecture", image: "/ProImgs/dubai/dubai11.webp" },
      { id: 12, title: "Smart Office", category: "Interior", image: "/ProImgs/dubai/dubai12.webp" },
      { id: 13, title: "Recreation Room", category: "Design", image: "/ProImgs/dubai/dubai13.webp" },
      { id: 14, title: "Outdoor Terrace", category: "Landscape", image: "/ProImgs/dubai/dubai14.webp" },
      { id: 15, title: "Hallway Lighting", category: "Design", image: "/ProImgs/dubai/dubai15.webp" },
      { id: 16, title: "Home Theatre", category: "Interior", image: "/ProImgs/dubai/dubai16.webp" },
      { id: 17, title: "Pool Side", category: "Exterior", image: "/ProImgs/dubai/dubai17.webp" },
      { id: 18, title: "Night View", category: "Architecture", image: "/ProImgs/dubai/dubai18.webp" },
    ],
    testimonial: {
      text: "Our office is now a place where people actually want to come and work. It has boosted our productivity and brand image.",
      name: "ramesh kumar",
      location: "delhi",
      userImg: "/Testimonials/user2.jpg"
    }
  },
  {
    id: 4,
    slug: "saota-indore",
    title: "indore residence",
    category: "residence",
    image: "/ProImgs/Proj/indore-card_result.webp",
    heroImg: "/ProImgs/saotaIndore/indore-hero_result.webp",
    mainImg: "/ProImgs/saotaIndore/indore4_result.webp",
    description: "Horizon Office is a futuristic workspace designed for high-performance teams. The interior promotes collaboration with open layouts and modular furniture. We integrated smart lighting systems that adjust based on natural light levels, significantly reducing energy consumption while maintaining a vibrant work environment.",
    stats: [
      { label: "status:", value: "under construction" },
      { label: "year:", value: "2027" },
      { label: "type:", value: "residence" },
      { label: "size:", value: "25,000 sq.ft." },
    ],
    gridImages: [
      { id: 1, title: "Tech Hub", category: "Interior", image: "/ProImgs/saotaIndore/indore1_result.webp" },
      { id: 2, title: "Main Lobby", category: "Design", image: "/ProImgs/saotaIndore/indore2_result.webp" },
      { id: 3, title: "Zen Garden", category: "Landscape", image: "/ProImgs/saotaIndore/indore3_result.webp" },
      { id: 5, title: "View 5", category: "Architecture", image: "/ProImgs/saotaIndore/indore5_result.webp" },
      { id: 6, title: "View 6", category: "Architecture", image: "/ProImgs/saotaIndore/indore6_result.webp" },
      { id: 7, title: "View 7", category: "Architecture", image: "/ProImgs/saotaIndore/indore7_result.webp" },
      { id: 8, title: "View 8", category: "Architecture", image: "/ProImgs/saotaIndore/indore8_result.webp" },
      { id: 9, title: "View 9", category: "Architecture", image: "/ProImgs/saotaIndore/indore9_result.webp" },
      { id: 10, title: "View 10", category: "Architecture", image: "/ProImgs/saotaIndore/indore10_result.webp" },
      { id: 11, title: "View 11", category: "Architecture", image: "/ProImgs/saotaIndore/indore11_result.webp" },
      { id: 12, title: "View 12", category: "Architecture", image: "/ProImgs/saotaIndore/indore12_result.webp" },
      { id: 13, title: "View 13", category: "Architecture", image: "/ProImgs/saotaIndore/indore13_result.webp" },
      { id: 14, title: "View 14", category: "Architecture", image: "/ProImgs/saotaIndore/indore14_result.webp" },
      { id: 15, title: "View 15", category: "Architecture", image: "/ProImgs/saotaIndore/indore15_result.webp" },
      { id: 16, title: "View 16", category: "Architecture", image: "/ProImgs/saotaIndore/indore16_result.webp" },
      { id: 17, title: "View 17", category: "Architecture", image: "/ProImgs/saotaIndore/indore17_result.webp" },
      { id: 18, title: "View 18", category: "Architecture", image: "/ProImgs/saotaIndore/indore18_result.webp" },
      { id: 19, title: "View 19", category: "Architecture", image: "/ProImgs/saotaIndore/indore19_result.webp" },
      { id: 20, title: "View 20", category: "Architecture", image: "/ProImgs/saotaIndore/indore20_result.webp" },
      { id: 21, title: "View 21", category: "Architecture", image: "/ProImgs/saotaIndore/indore21_result.webp" },
      { id: 22, title: "View 22", category: "Architecture", image: "/ProImgs/saotaIndore/indore22_result.webp" },
      { id: 23, title: "View 23", category: "Architecture", image: "/ProImgs/saotaIndore/indore23_result.webp" },
      { id: 24, title: "View 24", category: "Architecture", image: "/ProImgs/saotaIndore/indore24_result.webp" },
      { id: 25, title: "View 25", category: "Architecture", image: "/ProImgs/saotaIndore/indore25_result.webp" },
      { id: 26, title: "View 26", category: "Architecture", image: "/ProImgs/saotaIndore/indore26_result.webp" },
      { id: 27, title: "View 27", category: "Architecture", image: "/ProImgs/saotaIndore/indore27_result.webp" },
    ],
    testimonial: {
      text: "Our office is now a place where people actually want to come and work. It has boosted our productivity and brand image.",
      name: "ramesh kumar",
      location: "delhi",
      userImg: "/Testimonials/user2.jpg"
    }
  },
  {
    id: 5,
    slug: "hyderabad",
    title: "hyderabad residence",
    category: "residence",
    image: "/ProImgs/Proj/hyder-card_result.webp",
    heroImg: "/ProImgs/hyderabad/hyder-hero.webp",
    mainImg: "/ProImgs/hyderabad/hyder4.webp",
    description: "Horizon Office is a futuristic workspace designed for high-performance teams. The interior promotes collaboration with open layouts and modular furniture. We integrated smart lighting systems that adjust based on natural light levels, significantly reducing energy consumption while maintaining a vibrant work environment.",
    stats: [
      { label: "status:", value: "under construction" },
      { label: "year:", value: "2027" },
      { label: "type:", value: "residence" },
      { label: "size:", value: "14,000 sq.ft." },
    ],
    gridImages: [
      { id: 1, title: "Tech Hub", category: "Interior", image: "/ProImgs/hyderabad/hyder1.webp" },
      { id: 9, title: "Reception Area", category: "Design", image: "/ProImgs/hyderabad/hyder10.webp" },
      { id: 14, title: "Library", category: "Amenities", image: "/ProImgs/hyderabad/hyder15.webp" },
      { id: 2, title: "Main Lobby", category: "Design", image: "/ProImgs/hyderabad/hyder2.webp" },
      { id: 10, title: "Breakout Zone", category: "Interior", image: "/ProImgs/hyderabad/hyder11.webp" },
      { id: 13, title: "Parking Entrance", category: "Exterior", image: "/ProImgs/hyderabad/hyder14.webp" },
      { id: 15, title: "Night View", category: "Exterior", image: "/ProImgs/hyderabad/hyder1.webp" },
      { id: 12, title: "Terrace Garden", category: "Landscape", image: "/ProImgs/hyderabad/hyder13.webp" },
      { id: 11, title: "Manager Cabins", category: "Interior", image: "/ProImgs/hyderabad/hyder12.webp" },
      { id: 6, title: "Cafeteria", category: "Amenities", image: "/ProImgs/hyderabad/hyder7.webp" },
      { id: 8, title: "Courtyard", category: "Exterior", image: "/ProImgs/hyderabad/hyder9.webp" },
      { id: 7, title: "Executive Lounge", category: "Interior", image: "/ProImgs/hyderabad/hyder8.webp" },
      { id: 5, title: "Open Workspace", category: "Interior", image: "/ProImgs/hyderabad/hyder6.webp" },
      { id: 3, title: "Zen Garden", category: "Landscape", image: "/ProImgs/hyderabad/hyder3.webp" },
      { id: 4, title: "Conference Room", category: "Interior", image: "/ProImgs/hyderabad/hyder5.webp" },
    ],
    testimonial: {
      text: "Our office is now a place where people actually want to come and work. It has boosted our productivity and brand image.",
      name: "ramesh kumar",
      location: "delhi",
      userImg: "/Testimonials/user2.jpg"
    }
  },
  {
    id: 6,
    slug: "maharani-bagh-delhi",
    title: "delhi residence",
    category: "residence",
    image: "/ProImgs/Proj/maha-card_result.webp",
    heroImg: "/ProImgs/mahaDelhi/maha-hero.webp",
    mainImg: "/ProImgs/mahaDelhi/maha5.webp",
    description: "Horizon Office is a futuristic workspace designed for high-performance teams. The interior promotes collaboration with open layouts and modular furniture. We integrated smart lighting systems that adjust based on natural light levels, significantly reducing energy consumption while maintaining a vibrant work environment.",
    stats: [
      { label: "status:", value: "under construction" },
      { label: "year:", value: "2027" },
      { label: "type:", value: "residence" },
      { label: "size:", value: "20,000 sq.ft." },
    ],
    gridImages: [
      { id: 1, title: "Tech Hub", category: "Interior", image: "/ProImgs/mahaDelhi/maha1.webp" },
      { id: 2, title: "Main Lobby", category: "Design", image: "/ProImgs/mahaDelhi/maha2.webp" },
      { id: 3, title: "Zen Garden", category: "Landscape", image: "/ProImgs/mahaDelhi/maha3.webp" },
      { id: 4, title: "Living Area", category: "Interior", image: "/ProImgs/mahaDelhi/maha4.webp" },
      { id: 5, title: "Dining Room", category: "Interior", image: "/ProImgs/mahaDelhi/maha6.webp" },
      { id: 6, title: "Master Bedroom", category: "Interior", image: "/ProImgs/mahaDelhi/maha7.webp" },
      { id: 7, title: "Guest Room", category: "Interior", image: "/ProImgs/mahaDelhi/maha8.webp" },
      { id: 8, title: "Kitchen", category: "Interior", image: "/ProImgs/mahaDelhi/maha9.webp" },
      { id: 9, title: "Bathroom", category: "Design", image: "/ProImgs/mahaDelhi/maha10.webp" },
      { id: 10, title: "Balcony", category: "Exterior", image: "/ProImgs/mahaDelhi/maha11.webp" },
      { id: 11, title: "Terrace", category: "Exterior", image: "/ProImgs/mahaDelhi/maha12.webp" },
      { id: 12, title: "Home Theater", category: "Amenities", image: "/ProImgs/mahaDelhi/maha13.webp" },
      { id: 13, title: "Gym", category: "Amenities", image: "/ProImgs/mahaDelhi/maha14.webp" },
      { id: 14, title: "Study Room", category: "Interior", image: "/ProImgs/mahaDelhi/maha15.webp" },
      { id: 15, title: "Lounge", category: "Interior", image: "/ProImgs/mahaDelhi/maha16.webp" },
      { id: 16, title: "Pool Area", category: "Exterior", image: "/ProImgs/mahaDelhi/maha17.webp" },
      { id: 17, title: "Entrance", category: "Exterior", image: "/ProImgs/mahaDelhi/maha18.webp" },
      { id: 18, title: "Walk-in Closet", category: "Interior", image: "/ProImgs/mahaDelhi/maha19.webp" },
      { id: 19, title: "Staircase", category: "Design", image: "/ProImgs/mahaDelhi/maha20.webp" },
      { id: 20, title: "Night View", category: "Exterior", image: "/ProImgs/mahaDelhi/maha21.webp" },
    ],
    testimonial: {
      text: "Our office is now a place where people actually want to come and work. It has boosted our productivity and brand image.",
      name: "ramesh kumar",
      location: "delhi",
      userImg: "/Testimonials/user2.jpg"
    }
  },
  {
    id: 7,
    slug: "aura-sales-gallery",
    title: "aura sales gallery",
    category: "commercial space",
    image: "/ProImgs/Proj/aura-card_result.webp",
    heroImg: "/ProImgs/auraGurugram/aura-hero_result.webp",
    mainImg: "/ProImgs/auraGurugram/aura4_result.webp",
    description: "Horizon Office is a futuristic workspace designed for high-performance teams. The interior promotes collaboration with open layouts and modular furniture. We integrated smart lighting systems that adjust based on natural light levels, significantly reducing energy consumption while maintaining a vibrant work environment.",
    stats: [
      { label: "status:", value: "under construction" },
      { label: "year:", value: "2027" },
      { label: "type:", value: "sales gallery" },
      { label: "size:", value: "35,000 sq.ft." },
    ],
    gridImages: [
      { id: 1, title: "Tech Hub", category: "Interior", image: "/ProImgs/auraGurugram/aura1_result.webp" },
      { id: 2, title: "Main Lobby", category: "Design", image: "/ProImgs/auraGurugram/aura2_result.webp" },
      { id: 3, title: "Zen Garden", category: "Landscape", image: "/ProImgs/auraGurugram/aura3_result.webp" },
      { id: 4, title: "View 4", category: "Architecture", image: "/ProImgs/auraGurugram/aura4_result.webp" },
      { id: 5, title: "View 5", category: "Architecture", image: "/ProImgs/auraGurugram/aura5_result.webp" },
      { id: 6, title: "View 6", category: "Architecture", image: "/ProImgs/auraGurugram/aura6_result.webp" },
      { id: 7, title: "View 7", category: "Architecture", image: "/ProImgs/auraGurugram/aura7_result.webp" },
      { id: 8, title: "View 8", category: "Architecture", image: "/ProImgs/auraGurugram/aura8_result.webp" },
      { id: 9, title: "View 9", category: "Architecture", image: "/ProImgs/auraGurugram/aura9_result.webp" },
      { id: 10, title: "View 10", category: "Architecture", image: "/ProImgs/auraGurugram/aura10_result.webp" },
      { id: 11, title: "View 11", category: "Architecture", image: "/ProImgs/auraGurugram/aura11_result.webp" },
      { id: 12, title: "View 12", category: "Architecture", image: "/ProImgs/auraGurugram/aura12_result.webp" },
      { id: 13, title: "View 13", category: "Architecture", image: "/ProImgs/auraGurugram/aura13_result.webp" },
      { id: 14, title: "View 14", category: "Architecture", image: "/ProImgs/auraGurugram/aura14_result.webp" },
      { id: 15, title: "View 15", category: "Architecture", image: "/ProImgs/auraGurugram/aura15_result.webp" },
      { id: 16, title: "View 16", category: "Architecture", image: "/ProImgs/auraGurugram/aura16_result.webp" },
      { id: 17, title: "View 17", category: "Architecture", image: "/ProImgs/auraGurugram/aura17_result.webp" },
      { id: 18, title: "View 18", category: "Architecture", image: "/ProImgs/auraGurugram/aura18_result.webp" },
      { id: 19, title: "View 19", category: "Architecture", image: "/ProImgs/auraGurugram/aura19_result.webp" },
      { id: 20, title: "View 20", category: "Architecture", image: "/ProImgs/auraGurugram/aura20_result.webp" },
      { id: 21, title: "View 21", category: "Architecture", image: "/ProImgs/auraGurugram/aura21_result.webp" },
    ],
    testimonial: {
      text: "Our office is now a place where people actually want to come and work. It has boosted our productivity and brand image.",
      name: "ramesh kumar",
      location: "delhi",
      userImg: "/Testimonials/user2.jpg"
    }
  },
  {
    id: 8,
    slug: "bsml-corporate-office",
    title: "bsml corporate office",
    category: "corporate office",
    image: "/ProImgs/Proj/bansal-card_result.webp",
    heroImg: "/ProImgs/bansal/bansal-hero.webp",
    mainImg: "/ProImgs/bansal/bansal2.webp",
    description: "Horizon Office is a futuristic workspace designed for high-performance teams. The interior promotes collaboration with open layouts and modular furniture. We integrated smart lighting systems that adjust based on natural light levels, significantly reducing energy consumption while maintaining a vibrant work environment.",
    stats: [
      { label: "status:", value: "under construction" },
      { label: "year:", value: "2027" },
      { label: "type:", value: "corporate office" },
      { label: "size:", value: "35,000 sq.ft." },
    ],
    gridImages: [
      { id: 1, title: "Tech Hub", category: "Interior", image: "/ProImgs/bansal/bansal1.webp" },
      { id: 2, title: "Main Lobby", category: "Design", image: "/ProImgs/bansal/bansal3.webp" },
      { id: 3, title: "Zen Garden", category: "Landscape", image: "/ProImgs/bansal/bansal4.webp" },
      { id: 5, title: "Open Workspace", category: "Interior", image: "/ProImgs/bansal/bansal6.webp" },
      { id: 6, title: "Tech Hub", category: "Interior", image: "/ProImgs/bansal/bansal1.webp" },
      { id: 4, title: "Conference Room", category: "Interior", image: "/ProImgs/bansal/bansal5.webp" },
    ],
    testimonial: {
      text: "Our office is now a place where people actually want to come and work. It has boosted our productivity and brand image.",
      name: "ramesh kumar",
      location: "delhi",
      userImg: "/Testimonials/user2.jpg"
    }
  },

  {
    id: 9,
    slug: "kowori-residence",
    title: "kowori residence",
    category: "residence",
    image: "/ProImgs/Proj/kowari-card_result.webp",
    heroImg: "/ProImgs/kowori/kowari-hero.webp",
    mainImg: "/ProImgs/kowori/kowori-4.webp",
    description: "Horizon Office is a futuristic workspace designed for high-performance teams. The interior promotes collaboration with open layouts and modular furniture. We integrated smart lighting systems that adjust based on natural light levels, significantly reducing energy consumption while maintaining a vibrant work environment.",
    stats: [
      { label: "status:", value: "under construction" },
      { label: "year:", value: "2027" },
      { label: "type:", value: "residence" },
      { label: "size:", value: "6,000 sq.ft." },
    ],
    gridImages: [
      { id: 1, title: "Tech Hub", category: "Interior", image: "/ProImgs/kowori/kowori-1.webp" },
      { id: 2, title: "Main Lobby", category: "Design", image: "/ProImgs/kowori/kowari-2.webp" },
      { id: 3, title: "Zen Garden", category: "Landscape", image: "/ProImgs/kowori/kowori-3.webp" },
    ],
    testimonial: {
      text: "Our office is now a place where people actually want to come and work. It has boosted our productivity and brand image.",
      name: "ramesh kumar",
      location: "delhi",
      userImg: "/Testimonials/user2.jpg"
    }
  },
  {
    id: 10,
    slug: "parvsa",
    title: "delhi residence",
    category: "residence",
    image: "/ProImgs/Proj/Pravasa-card_result.webp",
    heroImg: "/ProImgs/pravasa/Pravasa-hero.webp",
    mainImg: "/ProImgs/pravasa/Parvasa1.webp",
    description: "Maisonluxe reimagined a classic Haussmann apartment into a refined haven of quiet modernity. The project involved full spatial planning, lighting design, and furniture selection — blending the romance of old Paris with contemporary restraint. By preserving historical character while refining material harmony, the apartment becomes a timeless expression of Parisian sophistication.",
    stats: [
      { label: "status:", value: "completed" },
      { label: "year:", value: "2025" },
      { label: "type", value: "residence" },
      { label: "size", value: "10,000 sq.ft." },
    ],
    gridImages: [
      { id: 1, title: "Grand Hall", category: "Interior", image: "/ProImgs/pravasa/Parvasa1.webp" },
      { id: 2, title: "Modern Kitchen", category: "Design", image: "/ProImgs/pravasa/Pravasa2.webp" },
      { id: 3, title: "Bedroom", category: "Detail", image: "/ProImgs/pravasa/Parvasa3.webp" },
    ],
    testimonial: {
      text: "Collective translated our vision into a home that feels both intimate and expansive. Every line and light angle feels intentional.",
      name: "ramesh kumar",
      location: "new delhi",
      userImg: "/Testimonials/user1.jpg"
    }
  },
  {
    id: 11,
    slug: "moradabad-residence",
    title: "moradabad residence",
    category: "residence",
    image: "/ProImgs/Proj/mehrotra-card_result.webp",
    heroImg: "/ProImgs/mehrotra/mehrotra-hero_result.webp",
    mainImg: "/ProImgs/mehrotra/mehrotra1_result.webp",
    description: "Harmony Resort is a sanctuary of peace designed to blend seamlessly with its tropical surroundings. The architecture uses sustainable materials to create a luxury experience that respects the local ecosystem. From the infinity pools to the open-air lobby, every element is designed to foster a deep connection with nature.",
    stats: [
      { label: "status:", value: "ongoing" },
      { label: "year:", value: "2026" },
      { label: "type:", value: "residence" },
      { label: "size:", value: "15,000 sq.ft." },
    ],
    gridImages: [
      // { id: 1, title: "Ocean Deck", category: "Exterior", image: "/ProImgs/mehrotra/mehrotra1_result.webp" },
      { id: 2, title: "Lounge Area", category: "Interior", image: "/ProImgs/mehrotra/mehrotra2_result.webp" },
      { id: 3, title: "Tropical Path", category: "Landscape", image: "/ProImgs/mehrotra/mehrotra3_result.webp" },
      // { id: 4, title: "Main Entrance", category: "Architecture", image: "/ProImgs/mehrotra/mehrotra4_result.webp" },
      { id: 5, title: "Guest Room", category: "Interior", image: "/ProImgs/mehrotra/mehrotra5_result.webp" },
      { id: 6, title: "Dining Hall", category: "Design", image: "/ProImgs/mehrotra/mehrotra6_result.webp" },
      { id: 7, title: "Poolside View", category: "Exterior", image: "/ProImgs/mehrotra/mehrotra7_result.webp" },
      { id: 8, title: "Garden Walkway", category: "Landscape", image: "/ProImgs/mehrotra/mehrotra8_result.webp" },
      { id: 9, title: "Modern Suite", category: "Interior", image: "/ProImgs/mehrotra/mehrotra9_result.webp" },
      { id: 10, title: "Reception", category: "Design", image: "/ProImgs/mehrotra/mehrotra10_result.webp" },
      { id: 11, title: "Terrace Garden", category: "Landscape", image: "/ProImgs/mehrotra/mehrotra11_result.webp" },
      { id: 12, title: "Facade Detail", category: "Architecture", image: "/ProImgs/mehrotra/mehrotra12_result.webp" },
      { id: 13, title: "Waiting Lounge", category: "Interior", image: "/ProImgs/mehrotra/mehrotra13_result.webp" },
      { id: 14, title: "Outdoor Deck", category: "Exterior", image: "/ProImgs/mehrotra/mehrotra14_result.webp" },
      { id: 15, title: "Pathway Lighting", category: "Design", image: "/ProImgs/mehrotra/mehrotra15_result.webp" },
      { id: 16, title: "Sky View", category: "Architecture", image: "/ProImgs/mehrotra/mehrotra16_result.webp" },
      { id: 17, title: "Water Feature", category: "Landscape", image: "/ProImgs/mehrotra/mehrotra17_result.webp" },
      // { id: 18, title: "Master Bedroom", category: "Interior", image: "/ProImgs/mehrotra/mehrotra18_result.webp" },
      { id: 19, title: "Courtyard", category: "Design", image: "/ProImgs/mehrotra/mehrotra19_result.webp" },
      { id: 20, title: "Balcony Perspective", category: "Architecture", image: "/ProImgs/mehrotra/mehrotra20_result.webp" },
      { id: 21, title: "Evening Glow", category: "Exterior", image: "/ProImgs/mehrotra/mehrotra21_result.webp" },
      { id: 22, title: "Lobby Lighting", category: "Interior", image: "/ProImgs/mehrotra/mehrotra22_result.webp" },
      { id: 23, title: "Nature Trail", category: "Landscape", image: "/ProImgs/mehrotra/mehrotra23_result.webp" },
      { id: 24, title: "Final Perspective", category: "Architecture", image: "/ProImgs/mehrotra/mehrotra24_result.webp" },
    ],
    testimonial: {
      text: "Incredible attention to detail. The fusion of modern aesthetics with functional luxury is something only they can pull off.",
      name: "ramesh kumar",
      location: "noida",
      userImg: "/Testimonials/user2.jpg"
    }
  },
  {
    id: 12,
    slug: "leeford-clinic",
    title: "leeford clinic",
    category: "clinic",
    image: "/ProImgs/Proj/leeford-card_result.webp",
    heroImg: "/ProImgs/leeford/leeford-hero_result.webp",
    mainImg: "/ProImgs/leeford/leeford3_result.webp",
    description: "Located on the banks of the Yamuna, River Apartments offers a panoramic view of the skyline. The design focuses on verticality and light, using floor-to-ceiling glass panels to bring the outside in. This project redefines urban living by providing a calm, breezy atmosphere in the heart of the city.",
    stats: [
      { label: "status:", value: "completed" },
      { label: "year:", value: "2024" },
      { label: "type:", value: "corporate office" },
      { label: "size:", value: "16,000 sq.ft." },
    ],
    gridImages: [
      { id: 1, title: "Skyline View", category: "Architecture", image: "/ProImgs/leeford/leeford1_result.webp" },
      { id: 2, title: "Reflective Pool", category: "Exterior", image: "/ProImgs/leeford/leeford2_result.webp" },
      { id: 4, title: "View 4", category: "Architecture", image: "/ProImgs/leeford/leeford4_result.webp" },
    ],
    testimonial: {
      text: "They turned a complex site into a masterpiece. Living here feels like being in a continuous dialogue with the city.",
      name: "amit sharma",
      location: "gurugram",
      userImg: "/Testimonials/user1.jpg"
    }
  },
  {
    id: 13,
    slug: "goel-residence",
    title: "raipur residence",
    category: "residence",
    image: "/ProImgs/Proj/goel-card_result.webp",
    heroImg: "/ProImgs/goel/goel-hero.webp",
    mainImg: "/ProImgs/goel/goel2.webp",
    description: "Horizon Office is a futuristic workspace designed for high-performance teams. The interior promotes collaboration with open layouts and modular furniture. We integrated smart lighting systems that adjust based on natural light levels, significantly reducing energy consumption while maintaining a vibrant work environment.",
    stats: [
      { label: "status:", value: "under construction" },
      { label: "year:", value: "2027" },
      { label: "type:", value: "residence" },
      { label: "size:", value: "20,000 sq.ft." },
    ],
    gridImages: [
      { id: 1, title: "Tech Hub", category: "Interior", image: "/ProImgs/goel/goel1.webp" },
      { id: 2, title: "Main Lobby", category: "Design", image: "/ProImgs/goel/goel4.webp" },
      { id: 3, title: "Zen Garden", category: "Landscape", image: "/ProImgs/goel/goel3.webp" },
    ],
    testimonial: {
      text: "Our office is now a place where people actually want to come and work. It has boosted our productivity and brand image.",
      name: "ramesh kumar",
      location: "delhi",
      userImg: "/Testimonials/user2.jpg"
    }
  },
  {
    id: 14,
    slug: "panchseel-delhi",
    title: "delhi residence",
    category: "residence",
    image: "/ProImgs/Proj/panchseel-card_result.webp",
    heroImg: "/ProImgs/panchseel/panchseel-hero.webp",
    mainImg: "/ProImgs/panchseel/panchseel4.webp",
    description: "Horizon Office is a futuristic workspace designed for high-performance teams. The interior promotes collaboration with open layouts and modular furniture. We integrated smart lighting systems that adjust based on natural light levels, significantly reducing energy consumption while maintaining a vibrant work environment.",
    stats: [
      { label: "status:", value: "under construction" },
      { label: "year:", value: "2027" },
      { label: "type:", value: "residence" },
      { label: "size:", value: "5,000 sq.ft." },
    ],
    gridImages: [
      { id: 1, title: "Tech Hub", category: "Interior", image: "/ProImgs/panchseel/panchseel1.webp" },
      { id: 2, title: "Main Lobby", category: "Design", image: "/ProImgs/panchseel/panchseel2.webp" },
      { id: 3, title: "Zen Garden", category: "Landscape", image: "/ProImgs/panchseel/panchseel3.webp" },
    ],
    testimonial: {
      text: "Our office is now a place where people actually want to come and work. It has boosted our productivity and brand image.",
      name: "ramesh kumar",
      location: "delhi",
      userImg: "/Testimonials/user2.jpg"
    }
  },
  {
    id: 15,
    slug: "amb-corporate-office",
    title: "amb corporate office",
    category: "corporate office",
    image: "/ProImgs/Proj/amb-card_result.webp",
    heroImg: "/ProImgs/amb/amb-hero.webp",
    mainImg: "/ProImgs/amb/amb2.webp",
    description: "Horizon Office is a futuristic workspace designed for high-performance teams. The interior promotes collaboration with open layouts and modular furniture. We integrated smart lighting systems that adjust based on natural light levels, significantly reducing energy consumption while maintaining a vibrant work environment.",
    stats: [
      { label: "status:", value: "under construction" },
      { label: "year:", value: "2027" },
      { label: "type:", value: "corporate office" },
      { label: "size:", value: "35,000 sq.ft." },
    ],
    gridImages: [
      { id: 1, title: "Tech Hub", category: "Interior", image: "/ProImgs/amb/amb1.webp" },
      { id: 2, title: "Main Lobby", category: "Design", image: "/ProImgs/amb/amb3.webp" },
      { id: 3, title: "Zen Garden", category: "Landscape", image: "/ProImgs/amb/amb4.webp" },
    ],
    testimonial: {
      text: "Our office is now a place where people actually want to come and work. It has boosted our productivity and brand image.",
      name: "ramesh kumar",
      location: "delhi",
      userImg: "/Testimonials/user2.jpg"
    }
  },
  {
    id: 16,
    slug: "westin-residence-gurugram",
    title: "the westin residence gurugram",
    category: "commercial space",
    image: "/ProImgs/Proj/whiteland-card_result.webp",
    heroImg: "/ProImgs/whiteland/whiteland-hero_result.webp",
    mainImg: "/ProImgs/whiteland/whiteland1_result.webp",
    description: "Horizon Office is a futuristic workspace designed for high-performance teams. The interior promotes collaboration with open layouts and modular furniture. We integrated smart lighting systems that adjust based on natural light levels, significantly reducing energy consumption while maintaining a vibrant work environment.",
    stats: [
      { label: "status:", value: "under construction" },
      { label: "year:", value: "2027" },
      { label: "type:", value: "sales gallery" },
      { label: "size:", value: "35,000 sq.ft." },
    ],
    gridImages: [
      { id: 1, title: "Tech Hub", category: "Interior", image: "/ProImgs/whiteland/whiteland2_result.webp" },
      { id: 2, title: "Main Lobby", category: "Design", image: "/ProImgs/whiteland/whiteland3_result.webp" },
      { id: 3, title: "Zen Garden", category: "Landscape", image: "/ProImgs/whiteland/whiteland4_result.webp" },
      // { id: 4, title: "View 4", category: "Architecture", image: "/ProImgs/whiteland/whiteland5_result.webp" },
      { id: 5, title: "View 5", category: "Architecture", image: "/ProImgs/whiteland/whiteland6_result.webp" },
      { id: 7, title: "View 7", category: "Architecture", image: "/ProImgs/whiteland/whiteland8_result.webp" },
      { id: 6, title: "View 6", category: "Architecture", image: "/ProImgs/whiteland/whiteland7_result.webp" },
    ],
    testimonial: {
      text: "Our office is now a place where people actually want to come and work. It has boosted our productivity and brand image.",
      name: "ramesh kumar",
      location: "delhi",
      userImg: "/Testimonials/user2.jpg"
    }
  },
  {
    id: 17,
    slug: "suncity’s-monarch-club",
    title: "suncity’s monarch club",
    category: "club house",
    image: "/ProImgs/Proj/monarch-card_result.webp",
    heroImg: "/ProImgs/monarch/monarch-hero_result.webp",
    mainImg: "/ProImgs/monarch/monarch1_result.webp",
    description: "Horizon Office is a futuristic workspace designed for high-performance teams. The interior promotes collaboration with open layouts and modular furniture. We integrated smart lighting systems that adjust based on natural light levels, significantly reducing energy consumption while maintaining a vibrant work environment.",
    stats: [
      { label: "status:", value: "under construction" },
      { label: "year:", value: "2027" },
      { label: "type:", value: "club house" },
      { label: "size:", value: "35,000 sq.ft." },
    ],
    gridImages: [
      // { id: 1, title: "Tech Hub", category: "Interior", image: "/ProImgs/monarch/monarch1_result.webp" },
      { id: 17, title: "Landscape Walkway", category: "Landscape", image: "/ProImgs/monarch/monarch17_result.webp" },
      { id: 15, title: "Library Nook", category: "Interior", image: "/ProImgs/monarch/monarch15_result.webp" },
      // { id: 14, title: "Terrace Deck", category: "Exterior", image: "/ProImgs/monarch/monarch14_result.webp" },
      { id: 10, title: "Outdoor Court", category: "Landscape", image: "/ProImgs/monarch/monarch10_result.webp" },
      { id: 3, title: "Zen Garden", category: "Landscape", image: "/ProImgs/monarch/monarch3_result.webp" },
      { id: 2, title: "Main Lobby", category: "Design", image: "/ProImgs/monarch/monarch2_result.webp" },
      { id: 5, title: "Social Lounge", category: "Interior", image: "/ProImgs/monarch/monarch5_result.webp" },
      { id: 6, title: "Clubhouse Cafe", category: "Design", image: "/ProImgs/monarch/monarch6_result.webp" },
      { id: 7, title: "Swimming Pool", category: "Exterior", image: "/ProImgs/monarch/monarch7_result.webp" },
      { id: 8, title: "Fitness Center", category: "Interior", image: "/ProImgs/monarch/monarch8_result.webp" },
      { id: 9, title: "Event Hall", category: "Design", image: "/ProImgs/monarch/monarch9_result.webp" },
      { id: 11, title: "Luxury Spa", category: "Interior", image: "/ProImgs/monarch/monarch11_result.webp" },
      { id: 4, title: "Grand Entrance", category: "Architecture", image: "/ProImgs/monarch/monarch4_result.webp" },
      { id: 12, title: "Billiards Room", category: "Design", image: "/ProImgs/monarch/monarch12_result.webp" },
      { id: 13, title: "Reception Desk", category: "Interior", image: "/ProImgs/monarch/monarch13_result.webp" },
      { id: 16, title: "Kids Zone", category: "Design", image: "/ProImgs/monarch/monarch16_result.webp" },
      { id: 18, title: "Private Suite", category: "Interior", image: "/ProImgs/monarch/monarch18_result.webp" },
      { id: 19, title: "Meeting Room", category: "Design", image: "/ProImgs/monarch/monarch19_result.webp" },
      { id: 20, title: "Facade Lighting", category: "Architecture", image: "/ProImgs/monarch/monarch20_result.webp" },
      { id: 21, title: "Indoor Games", category: "Design", image: "/ProImgs/monarch/monarch21_result.webp" },
      { id: 22, title: "Yoga Deck", category: "Landscape", image: "/ProImgs/monarch/monarch22_result.webp" },
      { id: 23, title: "Vibrant Lobby", category: "Interior", image: "/ProImgs/monarch/monarch23_result.webp" },
      { id: 24, title: "Evening View", category: "Exterior", image: "/ProImgs/monarch/monarch24_result.webp" },
      { id: 25, title: "Main Stairs", category: "Architecture", image: "/ProImgs/monarch/monarch25_result.webp" },
      { id: 26, title: "Sun Deck", category: "Exterior", image: "/ProImgs/monarch/monarch26_result.webp" },
      { id: 27, title: "Bar Area", category: "Interior", image: "/ProImgs/monarch/monarch27_result.webp" },
      { id: 28, title: "Water Body", category: "Landscape", image: "/ProImgs/monarch/monarch28_result.webp" },
      { id: 29, title: "Final Perspective", category: "Architecture", image: "/ProImgs/monarch/monarch29_result.webp" },
    ],
    testimonial: {
      text: "Our office is now a place where people actually want to come and work. It has boosted our productivity and brand image.",
      name: "ramesh kumar",
      location: "delhi",
      userImg: "/Testimonials/user2.jpg"
    }
  },
  {
    id: 18,
    slug: "grand-village",
    title: "grand village",
    category: "commercial space",
    image: "/ProImgs/Proj/grand-card_result.webp",
    heroImg: "/ProImgs/grand/grand-hero.webp",
    mainImg: "/ProImgs/grand/grand-hero.webp",
    description: "Horizon Office is a futuristic workspace designed for high-performance teams. The interior promotes collaboration with open layouts and modular furniture. We integrated smart lighting systems that adjust based on natural light levels, significantly reducing energy consumption while maintaining a vibrant work environment.",
    stats: [
      { label: "status:", value: "under construction" },
      { label: "year:", value: "2027" },
      { label: "type:", value: "retail space" },
      { label: "size:", value: "35,000 sq.ft." },
    ],
    gridImages: [
      { id: 1, title: "Tech Hub", category: "Interior", image: "/ProImgs/grand/grand2.webp" },
      { id: 2, title: "Main Lobby", category: "Design", image: "/ProImgs/grand/grand2.webp" },
      { id: 3, title: "Zen Garden", category: "Landscape", image: "/ProImgs/grand/grand4.webp" },
    ],
    testimonial: {
      text: "Our office is now a place where people actually want to come and work. It has boosted our productivity and brand image.",
      name: "ramesh kumar",
      location: "delhi",
      userImg: "/Testimonials/user2.jpg"
    }
  },

  {
    id: 19,
    slug: "adani-clubhouse",
    title: "adani clubhouse",
    category: "club house",
    image: "/adani clubhouse/0.webp",
    heroImg: "/adani clubhouse/1.webp",
    mainImg: "/adani clubhouse/2 (1).webp",
    gridImages: [
      { id: 1, title: "View 1", category: "Interior", image: "/adani clubhouse/2 (2).webp" },
      { id: 2, title: "View 2", category: "Design", image: "/adani clubhouse/2.webp" },
      { id: 3, title: "View 3", category: "Landscape", image: "/adani clubhouse/4 (1).webp" },
      { id: 4, title: "View 4", category: "Interior", image: "/adani clubhouse/4 (2).webp" },
      { id: 5, title: "View 5", category: "Design", image: "/adani clubhouse/4 (3).webp" },
      { id: 6, title: "View 6", category: "Interior", image: "/adani clubhouse/4 (4).webp" },
      { id: 7, title: "View 7", category: "Architecture", image: "/adani clubhouse/4 (5).webp" },
      { id: 8, title: "View 8", category: "Design", image: "/adani clubhouse/5.webp" },
      { id: 9, title: "View 9", category: "Interior", image: "/adani clubhouse/6 (1).webp" },
      { id: 10, title: "View 10", category: "Design", image: "/adani clubhouse/6 (2).webp" },
      { id: 11, title: "View 11", category: "Landscape", image: "/adani clubhouse/7.webp" },
      { id: 12, title: "View 12", category: "Design", image: "/adani clubhouse/0.webp" },
      { id: 13, title: "View 13", category: "Interior", image: "/adani clubhouse/5.webp" },
      { id: 14, title: "View 14", category: "Landscape", image: "/adani clubhouse/7.webp" },
      { id: 15, title: "View 8", category: "Design", image: "/adani clubhouse/0.webp" },
    ],
    testimonial: {
      userImg: "/adani clubhouse/2.webp"
    }
  },
  {
    id: 20,
    slug: "hyderabad-clubhouse",
    title: "hyderabad clubhouse",
    category: "club house",
    image: "/hyderabad clubhouse/1.webp",
    heroImg: "/hyderabad clubhouse/2.webp",
    mainImg: "/hyderabad clubhouse/3.webp",
    gridImages: [
      { id: 1, title: "View 1", category: "Interior", image: "/hyderabad clubhouse/4.webp" },
      { id: 2, title: "View 2", category: "Design", image: "/hyderabad clubhouse/5.webp" },
      { id: 3, title: "View 3", category: "Landscape", image: "/hyderabad clubhouse/6.webp" },
      { id: 4, title: "View 4", category: "Interior", image: "/hyderabad clubhouse/7.webp" },
      { id: 5, title: "View 5", category: "Design", image: "/hyderabad clubhouse/8.webp" },
      { id: 6, title: "View 6", category: "Interior", image: "/hyderabad clubhouse/1.webp" },
      { id: 7, title: "View 7", category: "Architecture", image: "/hyderabad clubhouse/7.webp" },
      { id: 8, title: "View 8", category: "Design", image: "/hyderabad clubhouse/8.webp" },
      { id: 9, title: "View 9", category: "Interior", image: "/hyderabad clubhouse/2.webp" },
      { id: 10, title: "View 10", category: "Design", image: "/hyderabad clubhouse/3.webp" },
      { id: 11, title: "View 11", category: "Landscape", image: "/hyderabad clubhouse/4.webp" },
      { id: 12, title: "View 12", category: "Design", image: "/hyderabad clubhouse/5.webp" },
      { id: 13, title: "View 13", category: "Interior", image: "/hyderabad clubhouse/6.webp" },
      { id: 14, title: "View 14", category: "Landscape", image: "/hyderabad clubhouse/2.webp" },
    ],
    testimonial: {
      userImg: "/hyderabad clubhouse/cover 6.webp"
    }
  },
  {
    id: 21,
    slug: "mapsko-clubhouse",
    title: "mapsko club house",
    category: "club house",
    image: "/mapsko clubhouse/1.webp",
    heroImg: "/mapsko clubhouse/2.webp",
    mainImg: "/mapsko clubhouse/3.webp",
    gridImages: [
      { id: 1, title: "View 1", category: "Interior", image: "/mapsko clubhouse/4.webp" },
      { id: 2, title: "View 2", category: "Design", image: "/mapsko clubhouse/5.webp" },
      { id: 3, title: "View 3", category: "Landscape", image: "/mapsko clubhouse/6.webp" },
      { id: 4, title: "View 4", category: "Interior", image: "/mapsko clubhouse/7.webp" },
      { id: 5, title: "View 5", category: "Design", image: "/mapsko clubhouse/8.webp" },
      { id: 6, title: "View 6", category: "Interior", image: "/mapsko clubhouse/9.webp" },
      { id: 7, title: "View 7", category: "Architecture", image: "/mapsko clubhouse/10.webp" },
      { id: 8, title: "View 8", category: "Design", image: "/mapsko clubhouse/11.webp" },
      { id: 9, title: "View 9", category: "Interior", image: "/mapsko clubhouse/12.webp" },
      { id: 10, title: "View 10", category: "Design", image: "/mapsko clubhouse/1.webp" },
      { id: 11, title: "View 11", category: "Landscape", image: "/mapsko clubhouse/6.webp" },
      { id: 12, title: "View 12", category: "Design", image: "/mapsko clubhouse/3.webp" },
      { id: 13, title: "View 13", category: "Interior", image: "/mapsko clubhouse/9.webp" },
      { id: 14, title: "View 14", category: "Landscape", image: "/mapsko clubhouse/8.webp" },
    ],
    testimonial: {
      userImg: "/mapsko clubhouse/12.webp"
    }
  },
  {
    id: 22,
    slug: "suncity-anamtam",
    title: "suncity anamtam",
    category: "club house",
    image: "/suncity anamtam/21.webp",
    heroImg: "/suncity anamtam/22.webp",
    mainImg: "/suncity anamtam/23.webp",
    gridImages: [
      { id: 1, title: "View 1", category: "Interior", image: "/suncity anamtam/1.webp" },
      { id: 2, title: "View 2", category: "Design", image: "/suncity anamtam/2.webp" },
      { id: 3, title: "View 3", category: "Landscape", image: "/suncity anamtam/3.webp" },
      { id: 4, title: "View 4", category: "Interior", image: "/suncity anamtam/4.webp" },
      { id: 5, title: "View 5", category: "Design", image: "/suncity anamtam/5.webp" },
      { id: 6, title: "View 6", category: "Interior", image: "/suncity anamtam/6.webp" },
      { id: 7, title: "View 7", category: "Architecture", image: "/suncity anamtam/7.webp" },
      { id: 8, title: "View 8", category: "Design", image: "/suncity anamtam/8.webp" },
      { id: 9, title: "View 9", category: "Interior", image: "/suncity anamtam/9.webp" },
      { id: 10, title: "View 10", category: "Design", image: "/suncity anamtam/10.webp" },
      { id: 11, title: "View 11", category: "Landscape", image: "/suncity anamtam/11.webp" },
      { id: 12, title: "View 12", category: "Design", image: "/suncity anamtam/12.webp" },
      { id: 13, title: "View 13", category: "Interior", image: "/suncity anamtam/13.webp" },
      { id: 14, title: "View 14", category: "Landscape", image: "/suncity anamtam/14.webp" },
    ],
    testimonial: {
      userImg: "/suncity anamtam/25.webp"
    }
  },

  // ── SALES GALLERY ──────────────────────────────
  {
    id: 23,
    slug: "bhumika-sales-gallery",
    title: "bhumika sales gallery",
    category: "commercial space",
    image: "/bhumika sales gallery/21.webp",
    heroImg: "/bhumika sales gallery/20.webp",
    mainImg: "/bhumika sales gallery/19.webp",
    gridImages: [
      { id: 1, title: "View 1", category: "Interior", image: "/bhumika sales gallery/1.webp" },
      { id: 2, title: "View 2", category: "Design", image: "/bhumika sales gallery/2.webp" },
      { id: 3, title: "View 3", category: "Landscape", image: "/bhumika sales gallery/3.webp" },
      { id: 4, title: "View 4", category: "Interior", image: "/bhumika sales gallery/4.webp" },
      { id: 5, title: "View 5", category: "Design", image: "/bhumika sales gallery/5.webp" },
      { id: 6, title: "View 6", category: "Interior", image: "/bhumika sales gallery/6.webp" },
      { id: 7, title: "View 7", category: "Architecture", image: "/bhumika sales gallery/7.webp" },
      { id: 8, title: "View 8", category: "Design", image: "/bhumika sales gallery/8.webp" },
      { id: 9, title: "View 9", category: "Interior", image: "/bhumika sales gallery/9.webp" },
      { id: 10, title: "View 10", category: "Design", image: "/bhumika sales gallery/10.webp" },
      { id: 11, title: "View 11", category: "Landscape", image: "/bhumika sales gallery/11.webp" },
      { id: 12, title: "View 12", category: "Design", image: "/bhumika sales gallery/12.webp" },
      { id: 13, title: "View 13", category: "Interior", image: "/bhumika sales gallery/13.webp" },
      { id: 14, title: "View 14", category: "Landscape", image: "/bhumika sales gallery/14.webp" },
    ],
    testimonial: { userImg: "/bhumika sales gallery/15.webp" }
  },
  {
    id: 24,
    slug: "elan-sales-gallery",
    title: "elan sales gallery",
    category: "commercial space",
    image: "/elan sales gallery/16.webp",
    heroImg: "/elan sales gallery/21.webp",
    mainImg: "/elan sales gallery/19.webp",
    gridImages: [
      { id: 1, title: "View 1", category: "Interior", image: "/elan sales gallery/1.webp" },
      { id: 2, title: "View 2", category: "Design", image: "/elan sales gallery/2.webp" },
      { id: 3, title: "View 3", category: "Landscape", image: "/elan sales gallery/3.webp" },
      { id: 4, title: "View 4", category: "Interior", image: "/elan sales gallery/4.webp" },
      { id: 5, title: "View 5", category: "Design", image: "/elan sales gallery/5.webp" },
      { id: 6, title: "View 6", category: "Interior", image: "/elan sales gallery/6.webp" },
      { id: 7, title: "View 7", category: "Architecture", image: "/elan sales gallery/7.webp" },
      { id: 8, title: "View 8", category: "Design", image: "/elan sales gallery/8.webp" },
      { id: 9, title: "View 9", category: "Interior", image: "/elan sales gallery/9.webp" },
      { id: 10, title: "View 10", category: "Design", image: "/elan sales gallery/10.webp" },
      { id: 11, title: "View 11", category: "Landscape", image: "/elan sales gallery/11.webp" },
      { id: 12, title: "View 12", category: "Design", image: "/elan sales gallery/12.webp" },
      { id: 13, title: "View 13", category: "Interior", image: "/elan sales gallery/13.webp" },
      { id: 14, title: "View 14", category: "Landscape", image: "/elan sales gallery/14.webp" },
    ],
    testimonial: { userImg: "/elan sales gallery/18.webp" }
  },
{
  id: 39,
  slug: "aryan-realty",
  title: "aryan realty",
  category: "commercial space",
  image: "/aryan realty/21.webp",
  heroImg: "/aryan realty/20.webp",
  mainImg: "/aryan realty/19.webp",
  gridImages: [
    { id: 1, title: "View 1", category: "Interior", image: "/aryan realty/1.webp" },
    { id: 2, title: "View 2", category: "Design", image: "/aryan realty/2.webp" },
    { id: 3, title: "View 3", category: "Landscape", image: "/aryan realty/3.webp" },
    { id: 4, title: "View 4", category: "Interior", image: "/aryan realty/4.webp" },
    { id: 5, title: "View 5", category: "Design", image: "/aryan realty/5.webp" },
    { id: 6, title: "View 6", category: "Interior", image: "/aryan realty/6.webp" },
    { id: 7, title: "View 7", category: "Architecture", image: "/aryan realty/7.webp" },
    { id: 8, title: "View 8", category: "Design", image: "/aryan realty/8.webp" },
    { id: 9, title: "View 9", category: "Interior", image: "/aryan realty/9.webp" },
    { id: 10, title: "View 10", category: "Design", image: "/aryan realty/10.webp" },
    { id: 11, title: "View 11", category: "Landscape", image: "/aryan realty/11.webp" },
    { id: 12, title: "View 12", category: "Design", image: "/aryan realty/12.webp" },
    { id: 13, title: "View 13", category: "Interior", image: "/aryan realty/13.webp" },
    { id: 14, title: "View 14", category: "Landscape", image: "/aryan realty/14.webp" },
  ],
  testimonial: { userImg: "/aryan realty/15.webp" }
},
  // ── CORPORATE OFFICE ────────────────────────────
  {
    id: 25,
    slug: "amritsar-office",
    title: "amritsar office",
    category: "corporate office",
    image: "/amritsar office/44.webp",
    heroImg: "/amritsar office/42.webp",
    mainImg: "/amritsar office/43.webp",
    gridImages: [
      { id: 1, title: "View 1", category: "Interior", image: "/amritsar office/1.webp" },
      { id: 2, title: "View 2", category: "Design", image: "/amritsar office/2.webp" },
      { id: 3, title: "View 3", category: "Landscape", image: "/amritsar office/3.webp" },
      { id: 4, title: "View 4", category: "Interior", image: "/amritsar office/4.webp" },
      { id: 5, title: "View 5", category: "Design", image: "/amritsar office/5.webp" },
      { id: 6, title: "View 6", category: "Interior", image: "/amritsar office/6.webp" },
      { id: 7, title: "View 7", category: "Architecture", image: "/amritsar office/7.webp" },
      { id: 8, title: "View 8", category: "Design", image: "/amritsar office/8.webp" },
      { id: 9, title: "View 9", category: "Interior", image: "/amritsar office/9.webp" },
      { id: 10, title: "View 10", category: "Design", image: "/amritsar office/10.webp" },
      { id: 11, title: "View 11", category: "Landscape", image: "/amritsar office/11.webp" },
      { id: 12, title: "View 12", category: "Design", image: "/amritsar office/12.webp" },
      { id: 13, title: "View 13", category: "Interior", image: "/amritsar office/13.webp" },
      { id: 14, title: "View 14", category: "Landscape", image: "/amritsar office/14.webp" },
    ],
    testimonial: { userImg: "/amritsar office/30.webp" }
  },
  {
    id: 26,
    slug: "elan-office",
    title: "elan office",
    category: "corporate office",
    image: "/elan office/17.webp",
    heroImg: "/elan office/16.webp",
    mainImg: "/elan office/15webp",
    gridImages: [
      { id: 1, title: "View 1", category: "Interior", image: "/elan office/1.webp" },
      { id: 2, title: "View 2", category: "Design", image: "/elan office/2.webp" },
      { id: 3, title: "View 3", category: "Landscape", image: "/elan office/3.webp" },
      { id: 4, title: "View 4", category: "Interior", image: "/elan office/4.webp" },
      { id: 5, title: "View 5", category: "Design", image: "/elan office/5.webp" },
      { id: 6, title: "View 6", category: "Interior", image: "/elan office/6.webp" },
      { id: 7, title: "View 7", category: "Architecture", image: "/elan office/7.webp" },
      { id: 8, title: "View 8", category: "Design", image: "/elan office/8.webp" },
      { id: 9, title: "View 9", category: "Interior", image: "/elan office/9.webp" },
      { id: 10, title: "View 10", category: "Design", image: "/elan office/10.webp" },
      { id: 11, title: "View 11", category: "Landscape", image: "/elan office/11.webp" },
      { id: 12, title: "View 12", category: "Design", image: "/elan office/12.webp" },
      { id: 13, title: "View 13", category: "Interior", image: "/elan office/13.webp" },
      { id: 14, title: "View 14", category: "Landscape", image: "/elan office/14.webp" },
    ],
    testimonial: { userImg: "/elan office/17.webp" }
  },
  {
    id: 27,
    slug: "essentia-office",
    title: "essentia office",
    category: "corporate office",
    image: "/essentia office/15.webp",
    heroImg: "/essentia office/12.webp",
    mainImg: "/essentia office/13.webp",
    gridImages: [
      { id: 1, title: "View 1", category: "Interior", image: "/essentia office/1.webp" },
      { id: 2, title: "View 2", category: "Design", image: "/essentia office/2.webp" },
      { id: 3, title: "View 3", category: "Landscape", image: "/essentia office/3.webp" },
      { id: 4, title: "View 4", category: "Interior", image: "/essentia office/4.webp" },
      { id: 5, title: "View 5", category: "Design", image: "/essentia office/5.webp" },
      { id: 6, title: "View 6", category: "Interior", image: "/essentia office/6.webp" },
      { id: 7, title: "View 7", category: "Architecture", image: "/essentia office/7.webp" },
      { id: 8, title: "View 8", category: "Design", image: "/essentia office/8.webp" },
      { id: 9, title: "View 9", category: "Interior", image: "/essentia office/9.webp" },
      { id: 10, title: "View 10", category: "Design", image: "/essentia office/10.webp" },
      { id: 11, title: "View 11", category: "Landscape", image: "/essentia office/11.webp" },
      { id: 12, title: "View 12", category: "Design", image: "/essentia office/12.webp" },
      { id: 13, title: "View 13", category: "Interior", image: "/essentia office/13.webp" },
      { id: 14, title: "View 14", category: "Landscape", image: "/essentia office/14.webp" },
    ],
    testimonial: { userImg: "/essentia office/1.webp" }
  },
  {
    id: 28,
    slug: "homeland-office",
    title: "homeland office",
    category: "corporate office",
    image: "/homeland office/0.webp",
    heroImg: "/homeland office/1.webp",
    mainImg: "/homeland office/2.webp",
    gridImages: [
      { id: 1, title: "View 1", category: "Interior", image: "/homeland office/1.webp" },
      { id: 2, title: "View 2", category: "Design", image: "/homeland office/2.webp" },
      { id: 3, title: "View 3", category: "Landscape", image: "/homeland office/3.webp" },
      { id: 4, title: "View 4", category: "Interior", image: "/homeland office/4.webp" },
      { id: 5, title: "View 5", category: "Design", image: "/homeland office/5.webp" },
      { id: 6, title: "View 6", category: "Interior", image: "/homeland office/6.webp" },
      { id: 7, title: "View 7", category: "Architecture", image: "/homeland office/0.webp" },
      { id: 8, title: "View 8", category: "Design", image: "/homeland office/1.webp" },
      { id: 9, title: "View 9", category: "Interior", image: "/homeland office/2.webp" },
      { id: 10, title: "View 10", category: "Design", image: "/homeland office/3.webp" },
      { id: 11, title: "View 11", category: "Landscape", image: "/homeland office/4.webp" },
      { id: 12, title: "View 12", category: "Design", image: "/homeland office/5.webp" },
      { id: 13, title: "View 13", category: "Interior", image: "/homeland office/6.webp" },
      { id: 14, title: "View 14", category: "Landscape", image: "/homeland office/7.webp" },
    ],
    testimonial: { userImg: "/homeland office/0.webp" }
  },
  {
    id: 29,
    slug: "mgp-office",
    title: "mgp office",
    category: "corporate office",
    image: "/mgp office/21.webp",
    heroImg: "/mgp office/20.webp",
    mainImg: "/mgp office/19.webp",
    gridImages: [
      { id: 1, title: "View 1", category: "Interior", image: "/mgp office/1.webp" },
      { id: 2, title: "View 2", category: "Design", image: "/mgp office/2.webp" },
      { id: 3, title: "View 3", category: "Landscape", image: "/mgp office/3.webp" },
      { id: 4, title: "View 4", category: "Interior", image: "/mgp office/4.webp" },
      { id: 5, title: "View 5", category: "Design", image: "/mgp office/5.webp" },
      { id: 6, title: "View 6", category: "Interior", image: "/mgp office/6.webp" },
      { id: 7, title: "View 7", category: "Architecture", image: "/mgp office/7.webp" },
      { id: 8, title: "View 8", category: "Design", image: "/mgp office/8.webp" },
      { id: 9, title: "View 9", category: "Interior", image: "/mgp office/9.webp" },
      { id: 10, title: "View 10", category: "Design", image: "/mgp office/10.webp" },
      { id: 11, title: "View 11", category: "Landscape", image: "/mgp office/11.webp" },
      { id: 12, title: "View 12", category: "Design", image: "/mgp office/12.webp" },
      { id: 13, title: "View 13", category: "Interior", image: "/mgp office/13.webp" },
      { id: 14, title: "View 14", category: "Landscape", image: "/mgp office/14.webp" },
    ],
    testimonial: { userImg: "/mgp office/18.webp" }
  },
  {
    id: 30,
    slug: "navraj-office-gurgaon",
    title: "navraj office gurgaon",
    category: "corporate office",
    image: "/navraj office gurgaon/16.webp",
    heroImg: "/navraj office gurgaon/15.webp",
    mainImg: "/navraj office gurgaon/14.webp",
    gridImages: [
      { id: 1, title: "View 1", category: "Interior", image: "/navraj office gurgaon/1.webp" },
      { id: 2, title: "View 2", category: "Design", image: "/navraj office gurgaon/2.webp" },
      { id: 3, title: "View 3", category: "Landscape", image: "/navraj office gurgaon/3.webp" },
      { id: 4, title: "View 4", category: "Interior", image: "/navraj office gurgaon/4.webp" },
      { id: 5, title: "View 5", category: "Design", image: "/navraj office gurgaon/5.webp" },
      { id: 6, title: "View 6", category: "Interior", image: "/navraj office gurgaon/6.webp" },
      { id: 7, title: "View 7", category: "Architecture", image: "/navraj office gurgaon/7.webp" },
      { id: 8, title: "View 8", category: "Design", image: "/navraj office gurgaon/8.webp" },
      { id: 9, title: "View 9", category: "Interior", image: "/navraj office gurgaon/9.webp" },
      { id: 10, title: "View 10", category: "Design", image: "/navraj office gurgaon/10.webp" },
      { id: 11, title: "View 11", category: "Landscape", image: "/navraj office gurgaon/11.webp" },
      { id: 12, title: "View 12", category: "Design", image: "/navraj office gurgaon/12.webp" },
      { id: 13, title: "View 13", category: "Interior", image: "/navraj office gurgaon/13.webp" },
      { id: 14, title: "View 14", category: "Landscape", image: "/navraj office gurgaon/14.webp" },
    ],
    testimonial: { userImg: "/navraj office gurgaon/15.webp" }
  },
  {
    id: 31,
    slug: "reach-office",
    title: "reach office",
    category: "corporate office",
    image: "/reach office/20.webp",
    heroImg: "/reach office/19.webp",
    mainImg: "/reach office/18.webp",
    gridImages: [
      { id: 1, title: "View 1", category: "Interior", image: "/reach office/1.webp" },
      { id: 2, title: "View 2", category: "Design", image: "/reach office/2.webp" },
      { id: 3, title: "View 3", category: "Landscape", image: "/reach office/3.webp" },
      { id: 4, title: "View 4", category: "Interior", image: "/reach office/4.webp" },
      { id: 5, title: "View 5", category: "Design", image: "/reach office/5.webp" },
      { id: 6, title: "View 6", category: "Interior", image: "/reach office/6.webp" },
      { id: 7, title: "View 7", category: "Architecture", image: "/reach office/7.webp" },
      { id: 8, title: "View 8", category: "Design", image: "/reach office/8.webp" },
      { id: 9, title: "View 9", category: "Interior", image: "/reach office/9.webp" },
      { id: 10, title: "View 10", category: "Design", image: "/reach office/10.webp" },
      { id: 11, title: "View 11", category: "Landscape", image: "/reach office/11.webp" },
      { id: 12, title: "View 12", category: "Design", image: "/reach office/12.webp" },
      { id: 13, title: "View 13", category: "Interior", image: "/reach office/13.webp" },
      { id: 14, title: "View 14", category: "Landscape", image: "/reach office/14.webp" },
    ],
    testimonial: { userImg: "/reach office/17.webp" }
  },
  {
    id: 32,
    slug: "schueco-office",
    title: "schueco office",
    category: "corporate office",
    image: "/schueco office/48.webp",
    heroImg: "/schueco office/47.webp",
    mainImg: "/schueco office/46.webp",
    gridImages: [
      { id: 1, title: "View 1", category: "Interior", image: "/schueco office/1.webp" },
      { id: 2, title: "View 2", category: "Design", image: "/schueco office/2.webp" },
      { id: 3, title: "View 3", category: "Landscape", image: "/schueco office/3.webp" },
      { id: 4, title: "View 4", category: "Interior", image: "/schueco office/4.webp" },
      { id: 5, title: "View 5", category: "Design", image: "/schueco office/5.webp" },
      { id: 6, title: "View 6", category: "Interior", image: "/schueco office/6.webp" },
      { id: 7, title: "View 7", category: "Architecture", image: "/schueco office/7.webp" },
      { id: 8, title: "View 8", category: "Design", image: "/schueco office/8.webp" },
      { id: 9, title: "View 9", category: "Interior", image: "/schueco office/9.webp" },
      { id: 10, title: "View 10", category: "Design", image: "/schueco office/10.webp" },
      { id: 11, title: "View 11", category: "Landscape", image: "/schueco office/11.webp" },
      { id: 12, title: "View 12", category: "Design", image: "/schueco office/12.webp" },
      { id: 13, title: "View 13", category: "Interior", image: "/schueco office/13.webp" },
      { id: 14, title: "View 14", category: "Landscape", image: "/schueco office/14.webp" },
    ],
    testimonial: { userImg: "/schueco office/32.webp" }
  },

  // ── RESIDENCE ──────────────────────────────────
  {
    id: 33,
    slug: "aralias-residence",
    title: "aralias residence",
    category: "residence",
    image: "/aralias residence/15.webp",
    heroImg: "/aralias residence/16.webp",
    mainImg: "/aralias residence/17.webp",
    gridImages: [
      { id: 1, title: "View 1", category: "Interior", image: "/aralias residence/1.webp" },
      { id: 2, title: "View 2", category: "Design", image: "/aralias residence/2.webp" },
      { id: 3, title: "View 3", category: "Landscape", image: "/aralias residence/3.webp" },
      { id: 4, title: "View 4", category: "Interior", image: "/aralias residence/4.webp" },
      { id: 5, title: "View 5", category: "Design", image: "/aralias residence/5.webp" },
      { id: 6, title: "View 6", category: "Interior", image: "/aralias residence/6.webp" },
      { id: 7, title: "View 7", category: "Architecture", image: "/aralias residence/7.webp" },
      { id: 8, title: "View 8", category: "Design", image: "/aralias residence/8.webp" },
      { id: 9, title: "View 9", category: "Interior", image: "/aralias residence/9.webp" },
      { id: 10, title: "View 10", category: "Design", image: "/aralias residence/10.webp" },
      { id: 11, title: "View 11", category: "Landscape", image: "/aralias residence/11.webp" },
      { id: 12, title: "View 12", category: "Design", image: "/aralias residence/12.webp" },
      { id: 13, title: "View 13", category: "Interior", image: "/aralias residence/13.webp" },
      { id: 14, title: "View 14", category: "Landscape", image: "/aralias residence/14.webp" },
    ],
    testimonial: { userImg: "/aralias residence/18.webp" }
  },
  {
    id: 34,
    slug: "camelias-residence",
    title: "camelias residence",
    category: "residence",
    image: "/camelias residence/15 copy.webp",
    heroImg: "/camelias residence/12.webp",
    mainImg: "/camelias residence/13.webp",
    gridImages: [
      { id: 1, title: "View 1", category: "Interior", image: "/camelias residence/1.webp" },
      { id: 2, title: "View 2", category: "Design", image: "/camelias residence/2.webp" },
      { id: 3, title: "View 3", category: "Landscape", image: "/camelias residence/3.webp" },
      { id: 4, title: "View 4", category: "Interior", image: "/camelias residence/4.webp" },
      { id: 5, title: "View 5", category: "Design", image: "/camelias residence/5.webp" },
      { id: 6, title: "View 6", category: "Interior", image: "/camelias residence/6.webp" },
      { id: 7, title: "View 7", category: "Architecture", image: "/camelias residence/7.webp" },
      { id: 8, title: "View 8", category: "Design", image: "/camelias residence/8.webp" },
      { id: 9, title: "View 9", category: "Interior", image: "/camelias residence/9.webp" },
      { id: 10, title: "View 10", category: "Design", image: "/camelias residence/10.webp" },
      { id: 11, title: "View 11", category: "Landscape", image: "/camelias residence/11.webp" },
      { id: 12, title: "View 12", category: "Design", image: "/camelias residence/12.webp" },
      { id: 13, title: "View 13", category: "Interior", image: "/camelias residence/13.webp" },
      { id: 14, title: "View 14", category: "Landscape", image: "/camelias residence/14.webp" },
    ],
    testimonial: { userImg: "/camelias residence/15.webp" }
  },
  {
    id: 37,
    slug: "camelias-residence",
    title: "camelias residence",
    category: "residence",
    image: "/camelias residence/33.webp",
    heroImg: "/camelias residence/32.webp",
    mainImg: "/camelias residence/31.webp",
    gridImages: [
      { id: 1, title: "View 1", category: "Interior", image: "/camelias residence/29.webp" },
      { id: 2, title: "View 2", category: "Design", image: "/camelias residence/28.webp" },
      { id: 3, title: "View 3", category: "Landscape", image: "/camelias residence/27.webp" },
      { id: 4, title: "View 4", category: "Interior", image: "/camelias residence/26.webp" },
      { id: 5, title: "View 5", category: "Design", image: "/camelias residence/25.webp" },
      { id: 6, title: "View 6", category: "Interior", image: "/camelias residence/24.webp" },
      { id: 7, title: "View 7", category: "Architecture", image: "/camelias residence/23.webp" },
      { id: 8, title: "View 8", category: "Design", image: "/camelias residence/22.webp" },
      { id: 9, title: "View 9", category: "Interior", image: "/camelias residence/21.webp" },
      { id: 10, title: "View 10", category: "Design", image: "/camelias residence/20.webp" },
      { id: 11, title: "View 11", category: "Landscape", image: "/camelias residence/19.webp" },
      { id: 12, title: "View 12", category: "Design", image: "/camelias residence/18.webp" },
      { id: 13, title: "View 13", category: "Interior", image: "/camelias residence/17.webp" },
      { id: 14, title: "View 14", category: "Landscape", image: "/camelias residence/17 copy.webp" },
    ],
    testimonial: { userImg: "/camelias residence/34.webp" }
  },
  {
    id: 38,
    slug: "camelias-residence",
    title: "camelias residence",
    category: "residence",
    image: "/camelias residence/2022_0704_08254200.webp",
    heroImg: "/camelias residence/2022_0704_08255300.webp",
    mainImg: "/camelias residence/2022_0704_08255600.webp",
    gridImages: [
      { id: 1, title: "View 1", category: "Interior", image: "/camelias residence/50.webp" },
      { id: 2, title: "View 2", category: "Design", image: "/camelias residence/51.webp" },
      { id: 3, title: "View 3", category: "Landscape", image: "/camelias residence/52.webp" },
      { id: 4, title: "View 4", category: "Interior", image: "/camelias residence/53.webp" },
      { id: 5, title: "View 5", category: "Design", image: "/camelias residence/54.webp" },
      { id: 6, title: "View 6", category: "Interior", image: "/camelias residence/55.webp" },
      { id: 7, title: "View 7", category: "Architecture", image: "/camelias residence/56.webp" },
      { id: 8, title: "View 8", category: "Design", image: "/camelias residence/57.webp" },
      { id: 9, title: "View 9", category: "Interior", image: "/camelias residence/58.webp" },
      { id: 10, title: "View 10", category: "Design", image: "/camelias residence/59.webp" },
      { id: 11, title: "View 11", category: "Landscape", image: "/camelias residence/60.webp" },
      { id: 12, title: "View 12", category: "Design", image: "/camelias residence/61.webp" },
      { id: 13, title: "View 13", category: "Interior", image: "/camelias residence/62.webp" },
      { id: 14, title: "View 14", category: "Landscape", image: "/camelias residence/2022_0702_23241800.webp" },
    ],
    testimonial: { userImg: "/camelias residence/2022_0702_23241500.webp" }
  },
  {
    id: 35,
    slug: "chattarpur farmhouse_",
    title: "chattarpur farmhouse_",
    category: "residence",
    image: "/new delhi farmhouse/nuye_1.webp",
    heroImg: "/new delhi farmhouse/nuye_7.webp",
    mainImg: "/new delhi farmhouse/nuye_15.webp",
    gridImages: [
      { id: 1, title: "View 1", category: "Interior", image: "/new delhi farmhouse/nuye_352.webp" },
      { id: 2, title: "View 2", category: "Design", image: "/new delhi farmhouse/nuye_196.webp" },
      { id: 3, title: "View 3", category: "Landscape", image: "/new delhi farmhouse/nuye_145.webp" },
      { id: 4, title: "View 4", category: "Interior", image: "/new delhi farmhouse/nuye_139.webp" },
      { id: 5, title: "View 5", category: "Design", image: "/new delhi farmhouse/nuye_74.webp" },
      { id: 6, title: "View 6", category: "Interior", image: "/new delhi farmhouse/nuye_62.webp" },
      { id: 7, title: "View 7", category: "Architecture", image: "/new delhi farmhouse/nuye_132.webp" },
      { id: 8, title: "View 8", category: "Design", image: "/new delhi farmhouse/nuye_124.webp" },
      { id: 9, title: "View 9", category: "Interior", image: "/new delhi farmhouse/nuye_108.webp" },
      { id: 10, title: "View 10", category: "Design", image: "/new delhi farmhouse/nuye_91.webp" },
      { id: 11, title: "View 11", category: "Landscape", image: "/new delhi farmhouse/nuye_58.webp" },
      { id: 12, title: "View 12", category: "Design", image: "/new delhi farmhouse/nuye_48.webp" },
      { id: 13, title: "View 13", category: "Interior", image: "/new delhi farmhouse/nuye_88.webp" },
      { id: 14, title: "View 14", category: "Landscape", image: "/new delhi farmhouse/nuye_96.webp" },
    ],
    testimonial: { userImg: "/new delhi farmhouse/nuye_112.webp" }
  },
  {
    id: 36,
    slug: "jaipur-residence",
    title: "jaipur residence",
    category: "residence",
    image: "/jaipur residence/21.webp",
    heroImg: "/jaipur residence/20.webp",
    mainImg: "/jaipur residence/19.webp",
    gridImages: [
      { id: 1, title: "View 1", category: "Interior", image: "/jaipur residence/1.webp" },
      { id: 2, title: "View 2", category: "Design", image: "/jaipur residence/2.webp" },
      { id: 3, title: "View 3", category: "Landscape", image: "/jaipur residence/3.webp" },
      { id: 4, title: "View 4", category: "Interior", image: "/jaipur residence/4.webp" },
      { id: 5, title: "View 5", category: "Design", image: "/jaipur residence/5.webp" },
      { id: 6, title: "View 6", category: "Interior", image: "/jaipur residence/6.webp" },
      { id: 7, title: "View 7", category: "Architecture", image: "/jaipur residence/7.webp" },
      { id: 8, title: "View 8", category: "Design", image: "/jaipur residence/8.webp" },
      { id: 9, title: "View 9", category: "Interior", image: "/jaipur residence/9.webp" },
      { id: 10, title: "View 10", category: "Design", image: "/jaipur residence/10.webp" },
      { id: 11, title: "View 11", category: "Landscape", image: "/jaipur residence/11.webp" },
      { id: 12, title: "View 12", category: "Design", image: "/jaipur residence/12.webp" },
      { id: 13, title: "View 13", category: "Interior", image: "/jaipur residence/13.webp" },
      { id: 14, title: "View 14", category: "Landscape", image: "/jaipur residence/14.webp" },
    ],
    testimonial: { userImg: "/jaipur residence/15.webp" }
  },
];