export const servicesData = [
  {
    id: 1,
    slug: "architectural-design",
    title: "architectural design",
    heroImg: "/architectrual/2.webp",
    introTitle: "From Concept to Construction: Our Holistic Architectural Design Approach",
    mainIntroImg: "/architectrual/3.webp",
    whyChoose: [
      "At Essentia, architecture is approached as the foundation of the entire spatial experience. Every project begins with a careful understanding of context, lifestyle, climate, and movement, allowing the built form to respond naturally to the way it will be inhabited. The process balances spatial planning with technical precision, ensuring that the structure is not only visually compelling but also practical and enduring.",
      "The team works across residences, commercial environments, and large-scale developments, shaping spaces that feel cohesive from every angle. Particular attention is given to proportion, circulation, natural light, materiality, and the relationship between interior and exterior volumes. Rather than following a fixed aesthetic, the approach is tailored to each project, creating architecture that feels personal and site-responsive.",
      "Through its integrated design-to-build framework, Essentia ensures that architectural intent is carried through seamlessly into execution, allowing every detail to be realised with clarity, consistency, and long-term functionality.",
    ],
    includes: [],
    otherServicesImg: "/architectrual/Bansal Office_Elevation front.webp",
    otherServices: [
      { title: "interior design", link: "/services/interior-design" },
      { title: "exterior design", link: "/services/exterior-design" },
      { title: "landscape design", link: "/services/landscape-design" },
      { title: "design to build execution", link: "/services/design-to-build" },
    ],
    process: [
      {
        step: "01",
        title: "conceptual design",
        desc: "Understanding the site, context, and client vision to develop a clear architectural direction rooted in functionality and spatial intent.",
        img: "/architectrual/2.webp",
      },
      {
        step: "02",
        title: "schematic design",
        desc: "Translating the concept into layouts, massing studies, and state-of-the-art 3D visualisations that bring the architecture to life with exceptional realism and clarity.",
        img: "/architectrual/3.webp",
      },
      {
        step: "03",
        title: "design development",
        desc: "Refining the approved scheme through detailed planning, material coordination, and technical integration across all architectural elements.",
        img: "/architectrual/4.webp",
      },
      {
        step: "04",
        title: "construction documentation",
        desc: "Preparing comprehensive technical drawings and execution-ready documentation to support accurate on-site implementation and approvals.",
        img: "/architectrual/5.webp",
      },
    ],

  },
  // {
  //   id: 2,
  //   slug: "exterior-design",
  //   title: "exterior design",
  //   heroImg: "/ServImgs/exterior/ext5.webp",
  //   introTitle: "Striking Facades and Timeless Exteriors: Redefining Your Building's Identity",
  //   mainIntroImg: "/ServImgs/exterior/ext2.webp",
  //   whyChoose: "Your building's exterior is its first impression. We specialize in designing striking, weather-resistant, and sustainable facades that blend aesthetic brilliance with structural integrity. We focus on materiality, lighting, and environmental context to create exteriors that truly stand out.",
  //   includes: [
  //     "Facade Design and Engineering",
  //     "Exterior Material and Texture Selection",
  //     "Architectural Lighting Design",
  //     "Weatherproofing and Climate-Responsive Design",
  //     "3D Elevation Rendering and Visualization",
  //   ],
  //   otherServicesImg: "/ServImgs/exterior/ext3.webp",
  //   otherServices: [
  //     { title: "architectural design", link: "/services/architectural-design" },
  //     { title: "interior design", link: "/services/interior-design" },
  //     { title: "landscape design", link: "/services/landscape-design" },
  //     { title: "design to build execution", link: "/services/design-to-build" },
  //   ],
  //   process: [
  //     {
  //       step: "01",
  //       title: "vision & context",
  //       desc: "Analyzing the building's context, local climate, and your aesthetic preferences to establish a strong design language for the facade.",
  //       img: "/ServImgs/exterior/ext1.webp",
  //     },
  //     {
  //       step: "02",
  //       title: "material & geometry",
  //       desc: "Developing the exterior geometry and selecting durable materials, from premium cladding and glazing to paints and natural stones.",
  //       img: "/ServImgs/exterior/ext2.webp",
  //     },
  //     {
  //       step: "03",
  //       title: "lighting & detailing",
  //       desc: "Integrating architectural lighting to highlight structural features and refining the technical details for seamless execution.",
  //       img: "/ServImgs/exterior/ext3.webp",
  //     },
  //     {
  //       step: "04",
  //       title: "final elevation & handover",
  //       desc: "Delivering comprehensive elevation drawings, 3D renders, and complete material specifications ready for the construction team.",
  //       img: "/ServImgs/exterior/ext4.webp",
  //     },
  //   ],

  // },
  {
    id: 3,
    slug: "landscape-design",
    title: "landscape design",
    heroImg: "/LANDSCAPE/1.webp",
    introTitle: "Harmonizing Nature and Architecture through Expert Landscaping",
    mainIntroImg: "/LANDSCAPE/2.webp",
    whyChoose: [
      "Landscape design at Essentia is developed as an extension of the built environment, creating outdoor spaces that feel connected, functional, and immersive. The approach considers how nature and architecture interact, shaping environments that encourage movement, pause, and everyday living. Whether for private homes, hospitality projects, or larger developments, each landscape is tailored to its surroundings and climatic conditions. ",
      "The process integrates hardscaping, planting, water features, lighting, and spatial zoning into one cohesive experience. Plant palettes are selected thoughtfully to ensure longevity and ease of maintenance, while pathways, seating areas, and outdoor transitions are designed to feel natural within the larger architectural language.",
      "Essentia approaches landscape design with the understanding that outdoor spaces evolve over time. The goal is to create environments that mature gracefully, adding depth and character to the overall project while maintaining a strong sense of balance between structure and nature. ",
    ],
    includes: [],
    otherServicesImg: "/LANDSCAPE/3.webp",
    otherServices: [
      { title: "architectural design", link: "/services/architectural-design" },
      { title: "interior design", link: "/services/interior-design" },
      { title: "exterior design", link: "/services/exterior-design" },
      { title: "design to build execution", link: "/services/design-to-build" },
    ],
    process: [
      {
        step: "01",
        title: "site research",
        desc: "Studying the site conditions, climate, and natural context to shape a landscape that responds intuitively to its environment.",
        img: "/LANDSCAPE/4.webp",
      },
      {
        step: "02",
        title: "landscape development",
        desc: "Planning greenery, pathways, water features, and outdoor zones to create a seamless connection between architecture and nature.",
        img: "/LANDSCAPE/5.webp",
      },
      {
        step: "03",
        title: "technical detailing",
        desc: "Developing detailed grading, irrigation, drainage, and lighting plans to ensure long-term functionality and maintenance efficiency.",
        img: "/LANDSCAPE/1.webp",
      },
      {
        step: "04",
        title: "execution support",
        desc: "Overseeing on-site implementation to ensure every landscape element is executed in alignment with the original design vision. ",
        img: "/LANDSCAPE/2.webp",
      },
    ],

  },
  // {
  //   id: 4,
  //   slug: "design-to-build",
  //   title: "design to build execution",
  //   heroImg: "/ServImgs/design/design1.webp",
  //   introTitle: "End-to-End Solutions: Seamless Design to Build Execution",
  //   mainIntroImg: "/ServImgs/design/design2.webp",
  //   whyChoose: "Bridging the gap between a drawing and a finished building. We take full responsibility from the first sketch to the final brick, ensuring quality and timeline control.",
  //   includes: [
  //     "Project Management and Scheduling",
  //     "On-site Supervision",
  //     "Material Procurement",
  //     "Quality Control and Safety Audits",
  //     "Turnkey Construction Solutions",
  //   ],
  //   otherServicesImg: "/ServImgs/design/design3.webp",
  //   otherServices: [
  //     { title: "architectural design", link: "/services/architectural-design" },
  //     { title: "interior design", link: "/services/interior-design" },
  //     { title: "exterior design", link: "/services/exterior-design" },
  //     { title: "landscape design", link: "/services/landscape-design" },
  //   ],
  //   process: [
  //     {
  //       step: "01",
  //       title: "strategic planning",
  //       desc: "Setting timelines, budgets, and milestones to ensure the project moves without friction.",
  //       img: "/ServImgs/design/design4.webp",
  //     },
  //     {
  //       step: "02",
  //       title: "resource mobilization",
  //       desc: "Coordinating with skilled craftsmen and procuring high-quality materials as per specifications.",
  //       img: "/ServImgs/design/design5.webp",
  //     },
  //     {
  //       step: "03",
  //       title: "construction phase",
  //       desc: "Executing the design on the ground with rigorous quality checks at every level of construction.",
  //       img: "/ServImgs/design/design1.webp",
  //     },
  //     {
  //       step: "04",
  //       title: "final handover",
  //       desc: "Final finishing, snag list clearance, and handing over the keys to your dream space.",
  //       img: "/ServImgs/design/design3.webp",
  //     },
  //   ],

  // },
  {
    id: 5,
    slug: "interior-design",
    title: "interior design",
    heroImg: "/INTERIOR DESIGN/4.webp",
    introTitle: "Crafting Intuitive Interiors: Clarity, Comfort, and Flow",
    mainIntroImg: "/INTERIOR DESIGN/5.webp",
    whyChoose: [
      "Essentia’s approach to interior design is rooted in creating environments that feel layered, intuitive, and deeply connected to the people using them. Beyond aesthetics, the focus lies in understanding how a space should function, flow, and evolve over time. Every interior is developed through a careful balance of spatial planning, material selection, lighting, furniture, and detailing, resulting in spaces that feel complete in every sense. ",
      "The design process is highly collaborative, allowing each project to reflect the client’s lifestyle while maintaining a strong architectural language. Materials are selected not only for their visual quality but also for their texture, longevity, and ability to age gracefully. Natural light, proportion, and movement through space are treated as key design elements throughout the process.",
      "From private residences to corporate environments, Essentia creates interiors that feel calm, refined, and easy to live in, where every layer contributes to a larger, cohesive narrative.",
    ],
    includes: [],
    otherServicesImg: "/INTERIOR DESIGN/6.webp",
    otherServices: [
      { title: "architectural design", link: "/services/architectural-design" },
      { title: "exterior design", link: "/services/exterior-design" },
      { title: "landscape design", link: "/services/landscape-design" },
      { title: "design to build execution", link: "/services/design-to-build" },
    ],
    process: [
      {
        step: "01",
        title: "mood & research",
        desc: "Establishing the visual direction through curated references, material exploration, and a deeper understanding of the client’s lifestyle and sensibilities.",
        img: "/INTERIOR DESIGN/7.webp",
      },
      {
        step: "02",
        title: "spatial development",
        desc: "Planning layouts and circulation with a focus on functionality, balance, and the natural flow of everyday living. ",
        img: "/INTERIOR DESIGN/8.webp",
      },
      {
        step: "03",
        title: "technical detailing",
        desc: "Developing detailed drawings and coordinated specifications to ensure precision across every stage of execution.",
        img: "/INTERIOR DESIGN/9.webp",
      },
      {
        step: "04",
        title: "on-site styling",
        desc: "Layering furniture, lighting, art, and décor on site to bring depth, warmth, and completion to the space.",
        img: "/INTERIOR DESIGN/10.webp",
      },
    ],

  },
  {
    id: 6,
    slug: "lighting",
    title: "lighting design",
    heroImg: "/lighting design/1.webp",
    introTitle: "Illuminating Spaces: Where Light Meets Design",
    mainIntroImg: "/lighting design/2.webp",
    whyChoose: [
      "Lighting plays a defining role in how a space is experienced, and Essentia approaches it as an integral part of the overall design process rather than a finishing layer. Each lighting plan is carefully developed to enhance architecture, highlight materials, and create atmosphere across different times of day. The balance between natural and artificial light is considered from the earliest stages of planning to ensure a cohesive spatial experience. ",
      "The approach combines technical precision with a strong understanding of mood and proportion. Ambient, accent, decorative, and task lighting are layered thoughtfully to support both functionality and visual comfort. Attention is also given to how light interacts with textures, surfaces, and volumes, allowing spaces to feel warm, balanced, and visually dynamic. ",
      "From residences and hospitality spaces to corporate environments, Essentia creates lighting strategies that elevate the experience of a space while remaining understated and seamlessly integrated into the larger design narrative.",
    ],
    includes: [],
    otherServicesImg: "/lighting design/3.webp",
    otherServices: [
      { title: "interior design", link: "/services/interior-design" },
      { title: "exterior design", link: "/services/exterior-design" },
      { title: "architectural design", link: "/services/architectural-design" },
      { title: "decor design", link: "/services/decor-design" },
    ],
    process: [
      {
        step: "01",
        title: "Spatial Understanding",
        desc: "Studying the architecture, material palette, and natural light movement to understand how illumination should shape the experience of the space. ",
        img: "/lighting design/4.webp",
      },
      {
        step: "02",
        title: "Lighting Strategy",
        desc: "Developing layered lighting plans that balance ambience, functionality, and visual comfort across different moods and times of day.",
        img: "/lighting design/5.webp",
      },
      {
        step: "03",
        title: "Fixture & Technical Coordination",
        desc: "Selecting fixtures and coordinating technical layouts to ensure seamless integration within ceilings, joinery, and architectural details.",
        img: "/lighting design/6.webp",
      },
      {
        step: "04",
        title: "On-Site Calibration",
        desc: "Fine-tuning beam angles, intensity, and placement on site to achieve the intended atmosphere with precision and balance. ",
        img: "/lighting design/7.webp",
      },
    ],

  },
  {
    id: 7,
    slug: "pmc",
    title: "project management consultancy",
    heroImg: "/turnkey pmc/1.webp",
    introTitle: "End-to-End Project Oversight: Precision, Control & Accountability",
    mainIntroImg: "/turnkey pmc/2.webp",
    whyChoose: [
      "Essentia’s Project Management Consultancy services are designed to bring clarity, coordination, and structure to every stage of a project. Acting as a central point of oversight, the team manages timelines, budgets, consultants, vendors, and site execution while ensuring that the original design intent remains uncompromised throughout the process.",
      "The role extends beyond administration, involving active problem-solving, detailed planning, and continuous communication between all stakeholders. Regular monitoring and reporting systems allow for transparency across every phase, helping anticipate challenges before they impact progress. With a strong understanding of both design and execution, the team is able to bridge the gap between concept and construction effectively.",
      "Essentia’s integrated approach allows projects to move forward with greater efficiency and accountability. The focus remains on delivering spaces that are not only visually aligned with the original vision but also completed with precision, consistency, and long-term functionality.",
    ],
    includes: [],
    otherServicesImg: "/turnkey pmc/3.webp",
    otherServices: [
      { title: "design to build execution", link: "/services/design-to-build" },
      { title: "contractor", link: "/services/contractor" },
      { title: "architectural design", link: "/services/architectural-design" },
      { title: "interior design", link: "/services/interior-design" },
    ],
    process: [
      {
        step: "01",
        title: "Project Planning",
        desc: "Establishing clear timelines, budgets, and execution roadmaps to create a structured foundation for the project from the outset. ",
        img: "/turnkey pmc/4.webp",
      },
      {
        step: "02",
        title: "Consultant Coordination",
        desc: "Managing communication across architects, contractors, vendors, and technical teams to ensure every moving part remains aligned. ",
        img: "/turnkey pmc/5.webp",
      },
      {
        step: "03",
        title: "Site Monitoring",
        desc: "Conducting regular site reviews and progress tracking to maintain quality standards, timelines, and design consistency throughout execution. ",
        img: "/turnkey pmc/6.webp",
      },
      {
        step: "04",
        title: "Delivery Management",
        desc: "Overseeing final execution, snagging, and handover processes to ensure the completed project is delivered seamlessly and without compromise.",
        img: "/turnkey pmc/7.webp",
      },
    ],

  },
  {
    id: 8,
    slug: "styling",
    title: "styling & staging",
    heroImg: "/Styling/01.webp",
    introTitle: "The Final Layer: Styling That Completes a Space",
    mainIntroImg: "/Styling/2.webp",
    whyChoose: [
      "Styling and staging at Essentia bring the final emotional and visual layer to a space, transforming it from completed to fully realised. The process involves carefully curating furniture, décor, art, textiles, lighting, and accessories to create environments that feel cohesive, inviting, and lived in. Every element is selected with attention to scale, texture, proportion, and the overall narrative of the space.",
      "Rather than treating styling as decoration alone, Essentia approaches it as an extension of the architectural and interior language. The placement of objects, layering of materials, and visual composition are all carefully considered to create balance and depth throughout the environment.",
      "Whether preparing a residence, hospitality project, show apartment, or corporate space, the focus remains on creating spaces that evoke warmth and character while remaining aligned with the larger design vision. The result is an environment that feels complete, intentional, and naturally resolved.",
    ],
    includes: [],
    otherServicesImg: "/Styling/36.webp",
    otherServices: [
      { title: "interior design", link: "/services/interior-design" },
      { title: "decor design", link: "/services/decor-design" },
      { title: "lighting design", link: "/services/lighting" },
      { title: "landscape design", link: "/services/landscape-design" },
    ],
    process: [
      {
        step: "01",
        title: "Visual Direction",
        desc: "Defining the overall mood of the space through references, textures, colour tones, and curated styling narratives.",
        img: "/Styling/10.webp",
      },
      {
        step: "02",
        title: "Furniture & Decor Curation",
        desc: "Selecting furniture, art, lighting, and objects that complement the architecture while adding depth and individuality to the space.",
        img: "/Styling/11.webp",
      },
      {
        step: "03",
        title: "Spatial Layering",
        desc: "Arranging pieces thoughtfully to create balance, movement, and a natural sense of flow across the environment. ",
        img: "/Styling/6.webp",
      },
      {
        step: "04",
        title: "Final Styling",
        desc: "Refining every detail on site, from object placement to soft furnishings, to ensure the space feels complete and lived in.",
        img: "/Styling/10.webp",
      },
    ],

  },
  {
    id: 9,
    slug: "mep",
    title: "mep design",
    heroImg: "/ServImgs/design/design1.webp",
    introTitle: "Mechanical, Electrical & Plumbing: The Backbone of Every Great Space",
    mainIntroImg: "/ServImgs/design/design2.webp",
    whyChoose: [
      "Essentia approaches MEP design with a strong emphasis on performance, coordination, and seamless integration within the larger architectural framework. Mechanical, electrical, and plumbing systems are carefully planned to support comfort, efficiency, safety, and long-term reliability without disrupting the visual integrity of the space.",
      "The process involves close coordination between consultants, architects, designers, and execution teams from the earliest stages of development. HVAC systems, electrical layouts, plumbing networks, lighting infrastructure, automation, and energy considerations are all integrated thoughtfully to ensure smooth day-to-day functionality. ",
      "Particular attention is given to precision in planning and execution, allowing technical systems to remain discreet while performing at the highest level. Through its integrated design-to-build approach, Essentia ensures that all MEP components align seamlessly with the overall project vision, resulting in environments that function effortlessly behind the scenes while maintaining a refined and cohesive spatial experience.",
    ],
    includes: [],
    otherServicesImg: "/ServImgs/design/design3.webp",
    otherServices: [
      { title: "architectural design", link: "/services/architectural-design" },
      { title: "interior design", link: "/services/interior-design" },
      { title: "design to build execution", link: "/services/design-to-build" },
      { title: "pmc", link: "/services/pmc" },
    ],
    process: [
      {
        step: "01",
        title: "Systems Planning",
        desc: "Understanding the project requirements to develop efficient mechanical, electrical, and plumbing strategies tailored to the space.",
        img: "/ServImgs/design/design4.webp",
      },
      {
        step: "02",
        title: "Technical Integration",
        desc: "Coordinating HVAC, electrical, plumbing, and automation systems with architectural and interior layouts for seamless functionality.",
        img: "/ServImgs/design/design5.webp",
      },
      {
        step: "03",
        title: "Detailed Documentation",
        desc: "Preparing precise technical drawings and service layouts to support accurate execution and long-term system performance.",
        img: "/ServImgs/design/design1.webp",
      },
      {
        step: "04",
        title: "Site Coordination",
        desc: "Working closely with on-site teams to ensure all systems are installed, tested, and integrated exactly as planned.",
        img: "/ServImgs/design/design3.webp",
      },
    ],

  },
  // {
  //   id: 10,
  //   slug: "decor-design",
  //   title: "decor design",
  //   heroImg: "/ServImgs/decor/decor-hero.webp", // Update path later
  //   introTitle: "Decor That Defines Living",
  //   mainIntroImg: "/ServImgs/decor/decor4.webp", // Update path later
  //   whyChoose: [
  //     "At essentia environments, decor is not an afterthought—it is the soul of a space. Every object, texture, and accent is thoughtfully curated to transform interiors into immersive experiences that reflect individuality and refined taste.",
  //     "We believe decor should tell a story—your story. Our design philosophy blends global aesthetics with local sensibilities, creating spaces that feel both timeless and deeply personal.",
  //     "From statement pieces to subtle accents, every element is selected to enhance harmony, balance, and visual depth.",
  //   ], includes: [
  //     "Curated Accessories",
  //     "Art & Wall Styling",
  //     "Soft Furnishings",
  //     "Lighting as Decor"
  //   ],
  //   otherServicesImg: "/ServImgs/decor/decor5.webp", // Update path later
  //   otherServices: [
  //     { title: "interior design", link: "/services/interior-design" },
  //     { title: "exterior design", link: "/services/exterior-design" },
  //     { title: "landscape design", link: "/services/landscape-design" },
  //     { title: "design to build execution", link: "/services/design-to-build" },
  //   ],

  //   // --- NAYE FIELDS FALLBACK KE LIYE ---
  //   processHeading: "what we offer",
  //   processSubHeading: "Handpicked decor elements, bespoke artworks, luxurious furnishings, and decorative lighting designed to elevate your space.",
  //   ctaText: "Bring Your Space to Life",
  //   // ------------------------------------

  //   process: [
  //     {
  //       step: "01",
  //       title: "Curated Accessories",
  //       desc: "Handpicked decor elements including sculptures, vases, art pieces, and collectibles that add character and sophistication.",
  //       img: "/ServImgs/decor/decor1.webp",
  //     },
  //     {
  //       step: "02",
  //       title: "Art & Wall Styling",
  //       desc: "Bespoke artworks, wall installations, and paneling solutions designed to create striking focal points.",
  //       img: "/ServImgs/decor/decor2.webp",
  //     },
  //     {
  //       step: "03",
  //       title: "Soft Furnishings",
  //       desc: "Luxurious cushions, throws, rugs, and drapery crafted with premium materials to add warmth and texture.",
  //       img: "/ServImgs/decor/decor6.webp",
  //     },
  //     {
  //       step: "04",
  //       title: "Lighting as Decor",
  //       desc: "Decorative lighting that doubles as art enhancing ambiance while elevating aesthetics.",
  //       img: "/ServImgs/decor/decor4.webp",
  //     },
  //   ],

  // },

// BUILD SERVICES
  {
    id: 11,
    slug: "high-end-projects",
    title: "high-end projects",
    heroImg: "/high end projects/1.webp",
    introTitle: "High-End Residential & Corporate Projects: Precision in Every Detail",
    mainIntroImg: "/high end projects/2.webp",
    whyChoose: [
      "Essentia undertakes high-end residential and corporate projects with a focus on precision, craftsmanship, and complete alignment between design and execution. Every project is approached with a deep understanding of detailing, materiality, and construction quality, ensuring that the final outcome reflects the original vision in its entirety.",
      "From private residences to premium commercial environments, the execution process is closely monitored across every stage. Skilled specialists, advanced manufacturing capabilities, and experienced site teams work together to deliver spaces with consistency and accuracy. Attention is given not only to major architectural elements but also to the finer details that shape the overall experience of a space.",
      "The integrated structure of Essentia allows for seamless coordination between design, procurement, manufacturing, and on-site execution. This ensures greater control over quality, timelines, and outcomes, resulting in environments that feel considered, complete, and built to endure over time.",
    ],
    includes: [],
    otherServicesImg: "/high end projects/3.webp",
    otherServices: [
      { title: "volume projects", link: "/services/volume-projects" },
      { title: "turnkey solutions", link: "/services/turnkey" },
      { title: "pmc", link: "/services/pmc" },
      { title: "design to build execution", link: "/services/design-to-build" },
    ],
    process: [
      {
        step: "01",
        title: "design alignment",
        desc: "Understanding the architectural vision, material language, and project expectations to establish a clear direction before execution begins.",
        img: "/high end projects/4.webp",
      },
      {
        step: "02",
        title: "Detailed Planning",
        desc: "Coordinating timelines, vendors, materials, and technical drawings to ensure every aspect of the project is planned with precision.",
        img: "/high end projects/5.webp",
      },
      {
        step: "03",
        title: "Site Execution",
        desc: "Managing on-site construction and craftsmanship closely to maintain quality, detailing, and consistency across every stage.",
        img: "/high end projects/6.webp",
      },
      {
        step: "04",
        title: "Final Completion",
        desc: "Overseeing finishing, installations, and final refinements to ensure the completed space reflects the original vision in its entirety.",
        img: "/high end projects/7.webp",
      },
    ],

  },
  {
    id: 12,
    slug: "volume-projects",
    title: "volume projects",
    heroImg: "/volume projects/1.webp",
    introTitle: "Volume Projects: Corporate, Hospitality & Developer-Scale Execution",
    mainIntroImg: "/volume projects/2.webp",
    whyChoose: [
      "Essentia brings the same level of precision and coordination to large-scale volume projects, combining efficiency with design integrity across multiple sites and typologies. The firm works extensively with developers, hospitality groups, and corporate clients, managing projects that require streamlined execution without compromising on quality or consistency. ",
      "The team has undertaken large-scale developments in partnership with leading developers such as M3M India, Whiteland Corporation, Suncity Projects, and Elan Group, delivering environments across residential, hospitality, and commercial sectors. Essentia also provides fit-out solutions on a lease basis for office spaces, offering clients greater operational flexibility while ensuring fully executed and ready-to-use environments.",
      "Strong project planning, centralised coordination, and integrated execution systems allow Essentia to manage scale efficiently while maintaining a consistent standard across every phase of delivery.",
    ],
    includes: [],
    otherServicesImg: "/volume projects/3.webp",
    otherServices: [
      { title: "high-end projects", link: "/services/high-end-projects" },
      { title: "turnkey solutions", link: "/services/turnkey" },
      { title: "pmc", link: "/services/pmc" },
      { title: "design to build execution", link: "/services/design-to-build" },
    ],
    process: [
      {
        step: "01",
        title: "project structuring",
        desc: "Establishing scalable execution strategies tailored to the size, timeline, and operational requirements of the development.",
        img: "/volume projects/4.webp",
      },
      {
        step: "02",
        title: "centralised coordination",
        desc: "Managing consultants, procurement, site teams, and vendor networks through a streamlined and closely monitored workflow.",
        img: "/volume projects/5.webp",
      },
      {
        step: "03",
        title: "large-scale execution",
        desc: "Executing multiple spaces or units simultaneously while maintaining consistency in quality, detailing, and delivery timelines.",
        img: "/volume projects/7.webp",
      },
      {
        step: "04",
        title: "handover & operational readiness",
        desc: "Ensuring every space is completed, tested, and ready for immediate use, including fit-out solutions delivered on a lease basis where required.",
        img: "/volume projects/8.webp",
      },
    ],

  },
  {
    id: 13,
    slug: "pmc-execution",
    title: "pmc (execution phase)",
    heroImg: "/turnkey pmc/8.webp",
    introTitle: "PMC Execution Phase: Keeping Every Site True to the Design Intent",
    mainIntroImg: "/turnkey pmc/1.webp",
    whyChoose: [
      "During the execution phase, Essentia’s PMC services focus on ensuring that every aspect of construction is carried out accurately, efficiently, and in alignment with the approved design intent. The team acts as a bridge between consultants, contractors, vendors, and clients, maintaining oversight across timelines, budgets, quality standards, and on-site coordination.",
      "Regular site inspections, progress tracking, technical reviews, and reporting systems help ensure transparency throughout the construction process. Any deviations are identified early and resolved proactively, reducing delays and maintaining consistency across execution. The approach combines technical understanding with practical site management, allowing projects to progress with clarity and discipline.",
      "With experience across both high-end and large-scale developments, Essentia brings a strong understanding of execution realities while safeguarding the overall vision of the project. The result is a smoother construction process and a final outcome delivered with greater precision and accountability.",
    ],
    includes: [],
    otherServicesImg: "/turnkey pmc/6.webp",
    otherServices: [
      { title: "pmc", link: "/services/pmc" },
      { title: "high-end projects", link: "/services/high-end-projects" },
      { title: "turnkey solutions", link: "/services/turnkey" },
      { title: "design to build execution", link: "/services/design-to-build" },
    ],
    process: [
      {
        step: "01",
        title: "execution planning",
        desc: "Reviewing drawings, timelines, and site requirements to establish a clear framework for smooth project execution.",
        img: "/turnkey pmc/5.webp",
      },
      {
        step: "02",
        title: "site coordination",
        desc: "Working closely with contractors, consultants, and vendors to ensure all on-site activities remain aligned with the approved plans.",
        img: "/turnkey pmc/4.webp",
      },
      {
        step: "03",
        title: "quality & progress monitoring",
        desc: "Conducting regular inspections and progress reviews to maintain execution standards, timelines, and technical accuracy.",
        img: "/turnkey pmc/3.webp",
      },
      {
        step: "04",
        title: "snagging & closure",
        desc: "Managing final corrections, testing, and handover processes to ensure the project is completed to the required standard.",
        img: "/turnkey pmc/2.webp",
      },
    ],

  },
  {
    id: 14,
    slug: "turnkey",
    title: "turnkey solutions",
    heroImg: "/turnkey pmc/1.webp",
    introTitle: "Turnkey Solutions: One Point of Responsibility, Complete Delivery",
    mainIntroImg: "/turnkey pmc/2.webp",
    whyChoose: [
      "Essentia’s turnkey solutions are designed to offer clients a seamless and fully integrated experience from concept development to final handover. By bringing design, manufacturing, procurement, project management, and execution under one framework, the firm creates a streamlined process with greater clarity, efficiency, and accountability at every stage.",
      "The turnkey model eliminates the need for multiple points of coordination, allowing all aspects of the project to work cohesively from the outset. Architecture, interiors, technical systems, furniture, finishes, and on-site execution are managed in alignment with a singular vision, ensuring consistency throughout the project lifecycle.",
      "With dedicated teams overseeing every phase, Essentia maintains close control over timelines, quality, budgeting, and execution standards. This integrated approach allows clients to move through the process with confidence, resulting in spaces that are fully realised, operationally ready, and reflective of the original design intent in every detail.",
    ],
    includes: [],
    otherServicesImg: "/turnkey pmc/3.webp",
    otherServices: [
      { title: "high-end projects", link: "/services/high-end-projects" },
      { title: "volume projects", link: "/services/volume-projects" },
      { title: "pmc", link: "/services/pmc" },
      { title: "design to build execution", link: "/services/design-to-build" },
    ],
    process: [
      {
        step: "01",
        title: "project briefing",
        desc: "Understanding the client’s requirements across design, functionality, timelines, and execution to establish a unified project direction.",
        img: "/turnkey pmc/4.webp",
      },
      {
        step: "02",
        title: "integrated planning",
        desc: "Bringing architecture, interiors, technical systems, procurement, and execution teams together under one coordinated framework.",
        img: "/turnkey pmc/5.webp",
      },
      {
        step: "03",
        title: "end-to-end execution",
        desc: "Managing every stage of the project, from manufacturing and site coordination to installations and finishing, through a single point of responsibility.",
        img: "/turnkey pmc/6.webp",
      },
      {
        step: "04",
        title: "ready-to-use delivery",
        desc: "Handing over fully completed spaces that are operational, cohesive, and aligned with the original vision down to the final detail.",
        img: "/turnkey pmc/8.webp",
      },
    ],

  },
  // FURNITURE SERVICES
  // {
  //   id: 15,
  //   slug: "furniture-catalogues",
  //   title: "furniture & products",
  //   heroImg: "/ServImgs/interior/inter1.webp",
  //   introTitle: "Essentia Home: A Curated World of Furniture & Décor",
  //   mainIntroImg: "/ServImgs/interior/inter4.webp",
  //   whyChoose: "Essentia's furniture and décor offering extends into a curated retail experience through Essentia Home, where clients can explore a wide range of products across categories. From statement furniture to everyday essentials, the collection reflects the same design sensibility and material focus seen across Essentia's projects. The range brings together in-house creations, international collaborations, and carefully sourced pieces, offering both ready selections and customisable options.",
  //   includes: [
  //     "Indoor & Outdoor Furniture",
  //     "Designer Collaborations",
  //     "Millwork, Wardrobes & DPC",
  //     "Vanity & Kitchen Solutions",
  //     "Décor & Soft Furnishings",
  //   ],
  //   otherServicesImg: "/ServImgs/decor/decor5.webp",
  //   otherServices: [
  //     { title: "interior design", link: "/services/interior-design" },
  //     { title: "decor design", link: "/services/decor-design" },
  //     { title: "furniture designers", link: "/services/furniture-designers" },
  //     { title: "styling & staging", link: "/services/styling" },
  //   ],
  //   process: [
  //     {
  //       step: "01",
  //       title: "product consultation",
  //       desc: "Understanding the space requirements, style preferences, and budget to guide product selection across all categories.",
  //       img: "/ServImgs/interior/inter3.webp",
  //     },
  //     {
  //       step: "02",
  //       title: "curation & selection",
  //       desc: "Exploring the Essentia Home catalogue alongside curated international collections to shortlist the right pieces.",
  //       img: "/ServImgs/decor/decor1.webp",
  //     },
  //     {
  //       step: "03",
  //       title: "customisation",
  //       desc: "Tailoring dimensions, materials, and finishes for bespoke requirements, coordinated with in-house manufacturing.",
  //       img: "/ServImgs/interior/inter5.webp",
  //     },
  //     {
  //       step: "04",
  //       title: "delivery & placement",
  //       desc: "Coordinating delivery, installation, and final placement of all furniture and décor elements within the space.",
  //       img: "/ServImgs/decor/decor4.webp",
  //     },
  //   ],

  // },
  {
    id: 16,
    slug: "furniture-designers",
    title: "designer furniture",
    heroImg: "/furniture/24.webp",
    introTitle: "Bespoke Furniture & Global Design Collaborations",
    mainIntroImg: "/furniture/23.webp",
    whyChoose: "Essentia collaborates with a range of international designers and brands to bring distinct perspectives into its furniture offering. Partnerships with designers such as Ferriani Sblogi, Armaan Bansal, Tomaya Studio and Luis Gimeno introduce varied design languages, while collaborations with global brands including Ichendorf Milano, Alessi, Tom Dixon and Rimadesio add depth to the collection. These associations span geographies, bringing together different influences while remaining aligned with Essentia's core design approach.",
    includes: [
      "Bespoke Furniture Design",
      "International Designer Collaborations",
      "Indoor & Outdoor Collections",
      "Material & Finish Customisation",
      "Global Brand Partnerships",
    ],
    otherServicesImg: "/furniture/22.webp",
    otherServices: [
      { title: "furniture catalogues", link: "/services/furniture-catalogues" },
      { title: "interior design", link: "/services/interior-design" },
      { title: "decor design", link: "/services/decor-design" },
      { title: "styling & staging", link: "/services/styling" },
    ],
    process: [
      {
        step: "01",
        title: "design brief",
        desc: "Collaborating closely with the client and project team to define the design language, material preferences, and functional requirements.",
        img: "/furniture/21.webp",
      },
      {
        step: "02",
        title: "designer matching",
        desc: "Connecting clients with the right designer or brand from Essentia's global network based on the project's aesthetic direction.",
        img: "/furniture/14.webp",
      },
      {
        step: "03",
        title: "development & sampling",
        desc: "Developing prototypes and material samples, refining the design through multiple rounds of review and approval.",
        img: "/furniture/16.webp",
      },
      {
        step: "04",
        title: "production & delivery",
        desc: "Manufacturing to the highest standard and coordinating delivery and placement within the project environment.",
        img: "/furniture/11.webp",
      },
    ],

  },
  {
    id: 17,
    slug: "furniture-overview",
    title: "products overview",
    heroImg: "/furniture/25.webp",
    introTitle: "Essentia Home: A Complete World of Furniture & Décor Products",
    mainIntroImg: "/furniture/19.webp",
    whyChoose: "Essentia's furniture and décor offering extends into a curated retail experience through Essentia Home, where clients can explore a wide range of products across categories. From statement furniture to everyday essentials, the collection reflects the same design sensibility and material focus seen across Essentia's projects. The range brings together in-house creations, international collaborations, and carefully sourced pieces, offering both ready selections and customisable options.",
    includes: [
      "Indoor & Outdoor Furniture",
      "Designer Collaborations",
      "Millwork, Wardrobes & Kitchen",
      "Vanity & Bathroom Solutions",
      "Décor & Soft Furnishings",
    ],
    otherServicesImg: "/furniture/13.webp",
    otherServices: [
      { title: "indoor furniture", link: "/services/furniture-indoor" },
      { title: "outdoor furniture", link: "/services/furniture-outdoor" },
      { title: "designer furniture", link: "/services/furniture-designer" },
      { title: "decor furniture", link: "/services/furniture-decor" },
    ],
    process: [
      {
        step: "01",
        title: "product consultation",
        desc: "Understanding the space requirements, style preferences, and budget to guide product selection across all categories.",
        img: "/furniture/16.webp",
      },
      {
        step: "02",
        title: "curation & selection",
        desc: "Exploring the Essentia Home catalogue alongside curated international collections to shortlist the right pieces.",
        img: "/furniture/1.webp",
      },
      {
        step: "03",
        title: "customisation",
        desc: "Tailoring dimensions, materials, and finishes for bespoke requirements, coordinated with in-house manufacturing.",
        img: "/furniture/8.webp",
      },
      {
        step: "04",
        title: "delivery & placement",
        desc: "Coordinating delivery, installation, and final placement of all furniture and décor elements within the space.",
        img: "/furniture/23.webp",
      },
    ],

  },
  {
    id: 18,
    slug: "furniture-indoor",
    title: "indoor furniture",
    heroImg: "/ServImgs/interior/inter1.webp",
    introTitle: "Indoor Furniture: Designed for Daily Living",
    mainIntroImg: "/ServImgs/interior/inter4.webp",
    whyChoose: "Essentia's indoor furniture is designed to integrate seamlessly into the spaces it inhabits, with a strong emphasis on proportion, comfort, and material integrity. Each piece is developed with an understanding of how it will be used daily, balancing form with function. The range spans living, dining, and bedroom furniture, with options that can be tailored to suit individual projects.",
    includes: [
      "Living Room Furniture",
      "Dining & Bedroom Collections",
      "Custom Sizing & Finishes",
      "Premium Material Selection",
      "Bespoke Upholstery Options",
    ],
    otherServicesImg: "/ServImgs/decor/decor5.webp",
    otherServices: [
      { title: "outdoor furniture", link: "/services/furniture-outdoor" },
      { title: "designer furniture", link: "/services/furniture-designer" },
      { title: "millwork & wardrobe", link: "/services/furniture-millwork" },
      { title: "products overview", link: "/services/furniture-overview" },
    ],
    process: [
      { step: "01", title: "space analysis", desc: "Understanding the room dimensions, usage patterns, and design brief to recommend the right furniture mix.", img: "/ServImgs/interior/inter3.webp" },
      { step: "02", title: "selection & customisation", desc: "Shortlisting pieces from the collection and customising sizes, materials, and finishes to suit the project.", img: "/ServImgs/decor/decor1.webp" },
      { step: "03", title: "production", desc: "Manufacturing each piece with careful attention to joinery, finish quality, and structural integrity.", img: "/ServImgs/interior/inter5.webp" },
      { step: "04", title: "delivery & placement", desc: "Delivering and placing all pieces within the space, ensuring everything sits in proportion and harmony.", img: "/ServImgs/decor/decor4.webp" },
    ],

  },
  {
    id: 19,
    slug: "furniture-outdoor",
    title: "outdoor furniture",
    heroImg: "/ServImgs/landscape/land1.webp",
    introTitle: "Outdoor Furniture: Durable Design for Open Spaces",
    mainIntroImg: "/ServImgs/landscape/land2.webp",
    whyChoose: "Outdoor furniture at Essentia is created to respond to both climate and context, ensuring durability without compromising on design. Materials are carefully selected to withstand changing weather conditions, while maintaining their character over time. The collection is designed to extend the living experience outdoors, whether for terraces, gardens, or poolside settings.",
    includes: [
      "Terrace & Garden Furniture",
      "Poolside Collections",
      "Weather-Resistant Materials",
      "Custom Sizing & Configurations",
      "Outdoor Lighting Accessories",
    ],
    otherServicesImg: "/ServImgs/landscape/land3.webp",
    otherServices: [
      { title: "indoor furniture", link: "/services/furniture-indoor" },
      { title: "landscape design", link: "/services/landscape-design" },
      { title: "products overview", link: "/services/furniture-overview" },
      { title: "decor furniture", link: "/services/furniture-decor" },
    ],
    process: [
      { step: "01", title: "site context", desc: "Assessing the outdoor environment, climate conditions, and spatial layout to guide the furniture selection.", img: "/ServImgs/landscape/land2.webp" },
      { step: "02", title: "material selection", desc: "Choosing weather-resistant materials — teak, aluminium, synthetic rattan — suited to the specific outdoor conditions.", img: "/ServImgs/landscape/land3.webp" },
      { step: "03", title: "customisation", desc: "Configuring layouts and custom dimensions to make the most of terrace, garden, or poolside spaces.", img: "/ServImgs/landscape/land4.webp" },
      { step: "04", title: "delivery & placement", desc: "Delivering and setting up all outdoor pieces, ensuring a cohesive and functional arrangement.", img: "/ServImgs/landscape/land5.webp" },
    ],

  },
  {
    id: 20,
    slug: "furniture-designer",
    title: "designer furniture",
    heroImg: "/ServImgs/decor/decor-hero.webp",
    introTitle: "Designer Furniture: Global Collaborations, Distinct Perspectives",
    mainIntroImg: "/ServImgs/decor/decor4.webp",
    whyChoose: "Essentia collaborates with a range of international designers and brands to bring distinct perspectives into its furniture offering. Partnerships with designers such as Ferriani Sblogi, Armaan Bansal, Tomaya Studio and Luis Gimeno introduce varied design languages, while collaborations with global brands including Ichendorf Milano, Alessi, Tom Dixon and Rimadesio add depth to the collection.",
    includes: [
      "International Designer Partnerships",
      "Global Brand Collaborations",
      "Bespoke Statement Pieces",
      "Limited Edition Collections",
      "Custom Project Commissions",
    ],
    otherServicesImg: "/ServImgs/decor/decor5.webp",
    otherServices: [
      { title: "indoor furniture", link: "/services/furniture-indoor" },
      { title: "outdoor furniture", link: "/services/furniture-outdoor" },
      { title: "products overview", link: "/services/furniture-overview" },
      { title: "decor furniture", link: "/services/furniture-decor" },
    ],
    process: [
      { step: "01", title: "design brief", desc: "Understanding the project vision and aesthetic direction to match clients with the right designer or brand from our global network.", img: "/ServImgs/decor/decor1.webp" },
      { step: "02", title: "designer matching", desc: "Connecting clients with the ideal designer or brand — spanning the UK, Italy, Spain, Russia, and beyond.", img: "/ServImgs/decor/decor2.webp" },
      { step: "03", title: "development & sampling", desc: "Developing prototypes and material samples, refining the design through multiple rounds of review and approval.", img: "/ServImgs/decor/decor6.webp" },
      { step: "04", title: "production & delivery", desc: "Manufacturing to the highest standard and coordinating delivery and placement within the project environment.", img: "/ServImgs/decor/decor4.webp" },
    ],

  },
  {
    id: 21,
    slug: "furniture-millwork",
    title: "millwork & wardrobe",
    heroImg: "/ServImgs/interior/inter1.webp",
    introTitle: "Millwork, Wardrobes & DPC: Precision Joinery for Every Space",
    mainIntroImg: "/ServImgs/interior/inter4.webp",
    whyChoose: "Essentia's millwork capabilities form a critical part of its build strength, allowing for complete control over detailing and execution. From doors and wall panelling to ceiling treatments and wardrobes, each element is developed with precision and consistency. The DPC (Doors, Panelling, Ceiling) offering ensures that architectural and interior details are seamlessly integrated into the space.",
    includes: [
      "Custom Wardrobes & Storage",
      "Door Design & Manufacturing",
      "Wall Panelling Solutions",
      "Ceiling Treatments & Coffers",
      "Premium Joinery & Finishes",
    ],
    otherServicesImg: "/ServImgs/interior/inter2.webp",
    otherServices: [
      { title: "indoor furniture", link: "/services/furniture-indoor" },
      { title: "kitchen furniture", link: "/services/furniture-kitchen" },
      { title: "vanity furniture", link: "/services/furniture-vanity" },
      { title: "products overview", link: "/services/furniture-overview" },
    ],
    process: [
      { step: "01", title: "design & planning", desc: "Developing detailed millwork drawings aligned with the interior and architectural intent of the space.", img: "/ServImgs/interior/inter3.webp" },
      { step: "02", title: "material selection", desc: "Choosing veneers, laminates, solid woods, and hardware that align with the design language and durability requirements.", img: "/ServImgs/interior/inter4.webp" },
      { step: "03", title: "manufacturing", desc: "Precision manufacturing in Essentia's in-house facility with stringent quality checks at every stage.", img: "/ServImgs/interior/inter5.webp" },
      { step: "04", title: "site installation", desc: "Expert on-site installation ensuring perfect fit, alignment, and finish across all millwork elements.", img: "/ServImgs/interior/inter2.webp" },
    ],

  },
  {
    id: 22,
    slug: "furniture-vanity",
    title: "vanity",
    heroImg: "/ServImgs/interior/inter1.webp",
    introTitle: "Vanity Design: Functional Elegance for Bathrooms & Dressing Areas",
    mainIntroImg: "/ServImgs/interior/inter4.webp",
    whyChoose: "Vanities at Essentia are designed as considered elements within larger environments, balancing utility with material expression. Each piece is tailored to the spatial layout and user requirements, integrating storage, surfaces, and finishes into a cohesive unit. Attention is given to proportions, detailing, and durability, ensuring that the vanity performs well in a high-use environment.",
    includes: [
      "Bathroom Vanity Units",
      "Dressing Table Design",
      "Integrated Storage Solutions",
      "Premium Surface Materials",
      "Custom Hardware & Fittings",
    ],
    otherServicesImg: "/ServImgs/interior/inter2.webp",
    otherServices: [
      { title: "kitchen furniture", link: "/services/furniture-kitchen" },
      { title: "millwork & wardrobe", link: "/services/furniture-millwork" },
      { title: "indoor furniture", link: "/services/furniture-indoor" },
      { title: "products overview", link: "/services/furniture-overview" },
    ],
    process: [
      { step: "01", title: "spatial brief", desc: "Understanding the bathroom or dressing area layout, user habits, and design direction to define the vanity concept.", img: "/ServImgs/interior/inter3.webp" },
      { step: "02", title: "design development", desc: "Developing the vanity configuration — storage layout, surface material, sink integration, and hardware selection.", img: "/ServImgs/interior/inter4.webp" },
      { step: "03", title: "manufacturing", desc: "Precision manufacturing with durable, moisture-resistant materials and high-quality finishes suited to bathroom environments.", img: "/ServImgs/interior/inter5.webp" },
      { step: "04", title: "installation", desc: "Expert installation with plumbing coordination, ensuring the vanity is fitted perfectly and functions seamlessly.", img: "/ServImgs/interior/inter2.webp" },
    ],

  },
  {
    id: 23,
    slug: "furniture-kitchen",
    title: "kitchen",
    heroImg: "/ServImgs/interior/inter1.webp",
    introTitle: "Kitchen Design: Functional, Refined & Built to Last",
    mainIntroImg: "/ServImgs/interior/inter4.webp",
    whyChoose: "Essentia's kitchens are developed with a focus on functionality, efficiency, and clean integration within the home. Layouts are carefully planned to optimise movement and usability, while materials and finishes are selected for durability and ease of maintenance. The design considers both everyday use and entertaining, creating spaces that feel practical yet well-resolved.",
    includes: [
      "Modular & Custom Kitchen Design",
      "Storage & Layout Optimisation",
      "Premium Countertop Materials",
      "Integrated Appliance Planning",
      "Joinery, Hardware & Finish Selection",
    ],
    otherServicesImg: "/ServImgs/interior/inter2.webp",
    otherServices: [
      { title: "vanity furniture", link: "/services/furniture-vanity" },
      { title: "millwork & wardrobe", link: "/services/furniture-millwork" },
      { title: "interior design", link: "/services/interior-design" },
      { title: "products overview", link: "/services/furniture-overview" },
    ],
    process: [
      { step: "01", title: "kitchen brief", desc: "Understanding cooking habits, storage needs, and aesthetic preferences to define the kitchen layout and design direction.", img: "/ServImgs/interior/inter3.webp" },
      { step: "02", title: "layout planning", desc: "Optimising the kitchen workflow — work triangle, storage zones, and appliance placement — for maximum efficiency.", img: "/ServImgs/interior/inter4.webp" },
      { step: "03", title: "material & finish selection", desc: "Selecting countertops, cabinet finishes, backsplashes, and hardware that balance beauty with everyday practicality.", img: "/ServImgs/interior/inter5.webp" },
      { step: "04", title: "manufacturing & installation", desc: "Precision manufacturing and expert installation with MEP coordination for a seamlessly completed kitchen.", img: "/ServImgs/interior/inter2.webp" },
    ],

  },
  {
    id: 24,
    slug: "furniture-decor",
    title: "decor",
    heroImg: "/ServImgs/decor/decor-hero.webp",
    introTitle: "Décor: The Objects & Accents That Complete a Space",
    mainIntroImg: "/ServImgs/decor/decor4.webp",
    whyChoose: "The décor offering at Essentia brings together objects, accessories, and accents that complete a space. From tabletop pieces and lighting to art and soft furnishings, each element is selected to complement the larger design narrative. Rather than acting as afterthoughts, these elements are used to add depth, contrast, and personality to a space, making it feel layered and complete.",
    includes: [
      "Tabletop & Decorative Objects",
      "Lighting as Décor",
      "Art & Wall Accessories",
      "Soft Furnishings & Textiles",
      "Global & In-House Curated Pieces",
    ],
    otherServicesImg: "/ServImgs/decor/decor5.webp",
    otherServices: [
      { title: "styling & staging", link: "/services/styling" },
      { title: "indoor furniture", link: "/services/furniture-indoor" },
      { title: "designer furniture", link: "/services/furniture-designer" },
      { title: "products overview", link: "/services/furniture-overview" },
    ],
    process: [
      { step: "01", title: "space reading", desc: "Reading the completed space to identify where décor can add depth, warmth, and visual interest without cluttering.", img: "/ServImgs/decor/decor1.webp" },
      { step: "02", title: "curation", desc: "Selecting objects, art, and soft furnishings from in-house and global collections that align with the design narrative.", img: "/ServImgs/decor/decor2.webp" },
      { step: "03", title: "layering", desc: "Placing each piece with intention — considering scale, proportion, colour, and the visual rhythm of the room.", img: "/ServImgs/decor/decor6.webp" },
      { step: "04", title: "final styling", desc: "Fine-tuning the placement of every element until the space feels cohesive, complete, and deeply personal.", img: "/ServImgs/decor/decor4.webp" },
    ],

  }
];